// Code generated by MockGen. DO NOT EDIT.
// Source: paired_agentred.go
//
// Generated by this command:
//
//	mockgen -source paired_agentred.go -destination mock_remote_device_repo/mock_paired_agentred.go
//

// Package mock_remote_device_repo is a generated GoMock package.
package mock_remote_device_repo

import (
	paired_agentred_entity "agentre/internal/model/entity/paired_agentred_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPairedAgentredRepo is a mock of PairedAgentredRepo interface.
type MockPairedAgentredRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPairedAgentredRepoMockRecorder
	isgomock struct{}
}

// MockPairedAgentredRepoMockRecorder is the mock recorder for MockPairedAgentredRepo.
type MockPairedAgentredRepoMockRecorder struct {
	mock *MockPairedAgentredRepo
}

// NewMockPairedAgentredRepo creates a new mock instance.
func NewMockPairedAgentredRepo(ctrl *gomock.Controller) *MockPairedAgentredRepo {
	mock := &MockPairedAgentredRepo{ctrl: ctrl}
	mock.recorder = &MockPairedAgentredRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPairedAgentredRepo) EXPECT() *MockPairedAgentredRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPairedAgentredRepo) Create(ctx context.Context, p *paired_agentred_entity.PairedAgentred) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPairedAgentredRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPairedAgentredRepo)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockPairedAgentredRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPairedAgentredRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPairedAgentredRepo)(nil).Delete), ctx, id)
}

// FindByURL mocks base method.
func (m *MockPairedAgentredRepo) FindByURL(ctx context.Context, url string) (*paired_agentred_entity.PairedAgentred, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByURL", ctx, url)
	ret0, _ := ret[0].(*paired_agentred_entity.PairedAgentred)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByURL indicates an expected call of FindByURL.
func (mr *MockPairedAgentredRepoMockRecorder) FindByURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByURL", reflect.TypeOf((*MockPairedAgentredRepo)(nil).FindByURL), ctx, url)
}

// Get mocks base method.
func (m *MockPairedAgentredRepo) Get(ctx context.Context, id int64) (*paired_agentred_entity.PairedAgentred, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*paired_agentred_entity.PairedAgentred)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPairedAgentredRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPairedAgentredRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockPairedAgentredRepo) List(ctx context.Context) ([]*paired_agentred_entity.PairedAgentred, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*paired_agentred_entity.PairedAgentred)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPairedAgentredRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPairedAgentredRepo)(nil).List), ctx)
}

// Rename mocks base method.
func (m *MockPairedAgentredRepo) Rename(ctx context.Context, id int64, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockPairedAgentredRepoMockRecorder) Rename(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockPairedAgentredRepo)(nil).Rename), ctx, id, name)
}

// UpdateEndpoint mocks base method.
func (m *MockPairedAgentredRepo) UpdateEndpoint(ctx context.Context, id int64, url, daemonFingerprint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEndpoint", ctx, id, url, daemonFingerprint)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEndpoint indicates an expected call of UpdateEndpoint.
func (mr *MockPairedAgentredRepoMockRecorder) UpdateEndpoint(ctx, id, url, daemonFingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEndpoint", reflect.TypeOf((*MockPairedAgentredRepo)(nil).UpdateEndpoint), ctx, id, url, daemonFingerprint)
}

// UpdateLastSeen mocks base method.
func (m *MockPairedAgentredRepo) UpdateLastSeen(ctx context.Context, id, ts int64, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastSeen", ctx, id, ts, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastSeen indicates an expected call of UpdateLastSeen.
func (mr *MockPairedAgentredRepoMockRecorder) UpdateLastSeen(ctx, id, ts, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastSeen", reflect.TypeOf((*MockPairedAgentredRepo)(nil).UpdateLastSeen), ctx, id, ts, lastError)
}

// UpdateTLS mocks base method.
func (m *MockPairedAgentredRepo) UpdateTLS(ctx context.Context, id int64, mode, pem string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTLS", ctx, id, mode, pem)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTLS indicates an expected call of UpdateTLS.
func (mr *MockPairedAgentredRepoMockRecorder) UpdateTLS(ctx, id, mode, pem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTLS", reflect.TypeOf((*MockPairedAgentredRepo)(nil).UpdateTLS), ctx, id, mode, pem)
}
