// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source types.go -destination mock_prober_test.go -package agent_backend_svc -mock_names Prober=mockProber
//

// Package agent_backend_svc is a generated GoMock package.
package agent_backend_svc

import (
	context "context"
	agent_backend_entity "github.com/agentre-ai/agentre/internal/model/entity/agent_backend_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// mockProber is a mock of Prober interface.
type mockProber struct {
	ctrl     *gomock.Controller
	recorder *mockProberMockRecorder
	isgomock struct{}
}

// mockProberMockRecorder is the mock recorder for mockProber.
type mockProberMockRecorder struct {
	mock *mockProber
}

// NewmockProber creates a new mock instance.
func NewmockProber(ctrl *gomock.Controller) *mockProber {
	mock := &mockProber{ctrl: ctrl}
	mock.recorder = &mockProberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *mockProber) EXPECT() *mockProberMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *mockProber) Run(ctx context.Context, b *agent_backend_entity.AgentBackend, deps ProbeDeps) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, b, deps)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *mockProberMockRecorder) Run(ctx, b, deps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*mockProber)(nil).Run), ctx, b, deps)
}
