// Code generated by MockGen. DO NOT EDIT.
// Source: hook.go
//
// Generated by this command:
//
//	mockgen -source hook.go -destination mock_hook_repo/mock_hook.go
//

// Package mock_hook_repo is a generated GoMock package.
package mock_hook_repo

import (
	hook_entity "agentre/internal/model/entity/hook_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHookSourceRepo is a mock of HookSourceRepo interface.
type MockHookSourceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHookSourceRepoMockRecorder
	isgomock struct{}
}

// MockHookSourceRepoMockRecorder is the mock recorder for MockHookSourceRepo.
type MockHookSourceRepoMockRecorder struct {
	mock *MockHookSourceRepo
}

// NewMockHookSourceRepo creates a new mock instance.
func NewMockHookSourceRepo(ctrl *gomock.Controller) *MockHookSourceRepo {
	mock := &MockHookSourceRepo{ctrl: ctrl}
	mock.recorder = &MockHookSourceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookSourceRepo) EXPECT() *MockHookSourceRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHookSourceRepo) Create(ctx context.Context, s *hook_entity.HookSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHookSourceRepoMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHookSourceRepo)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockHookSourceRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHookSourceRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHookSourceRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockHookSourceRepo) Find(ctx context.Context, id int64) (*hook_entity.HookSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*hook_entity.HookSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockHookSourceRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockHookSourceRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockHookSourceRepo) FindByName(ctx context.Context, name string) (*hook_entity.HookSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*hook_entity.HookSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockHookSourceRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockHookSourceRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockHookSourceRepo) List(ctx context.Context) ([]*hook_entity.HookSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*hook_entity.HookSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHookSourceRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHookSourceRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockHookSourceRepo) Update(ctx context.Context, s *hook_entity.HookSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHookSourceRepoMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHookSourceRepo)(nil).Update), ctx, s)
}

// MockHookRuleRepo is a mock of HookRuleRepo interface.
type MockHookRuleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHookRuleRepoMockRecorder
	isgomock struct{}
}

// MockHookRuleRepoMockRecorder is the mock recorder for MockHookRuleRepo.
type MockHookRuleRepoMockRecorder struct {
	mock *MockHookRuleRepo
}

// NewMockHookRuleRepo creates a new mock instance.
func NewMockHookRuleRepo(ctrl *gomock.Controller) *MockHookRuleRepo {
	mock := &MockHookRuleRepo{ctrl: ctrl}
	mock.recorder = &MockHookRuleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookRuleRepo) EXPECT() *MockHookRuleRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHookRuleRepo) Create(ctx context.Context, r *hook_entity.HookRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHookRuleRepoMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHookRuleRepo)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockHookRuleRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHookRuleRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHookRuleRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockHookRuleRepo) Find(ctx context.Context, id int64) (*hook_entity.HookRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*hook_entity.HookRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockHookRuleRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockHookRuleRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockHookRuleRepo) List(ctx context.Context) ([]*hook_entity.HookRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*hook_entity.HookRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHookRuleRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHookRuleRepo)(nil).List), ctx)
}

// ListBySource mocks base method.
func (m *MockHookRuleRepo) ListBySource(ctx context.Context, sourceID int64) ([]*hook_entity.HookRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySource", ctx, sourceID)
	ret0, _ := ret[0].([]*hook_entity.HookRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySource indicates an expected call of ListBySource.
func (mr *MockHookRuleRepoMockRecorder) ListBySource(ctx, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySource", reflect.TypeOf((*MockHookRuleRepo)(nil).ListBySource), ctx, sourceID)
}

// NextSortOrder mocks base method.
func (m *MockHookRuleRepo) NextSortOrder(ctx context.Context, sourceID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSortOrder", ctx, sourceID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSortOrder indicates an expected call of NextSortOrder.
func (mr *MockHookRuleRepoMockRecorder) NextSortOrder(ctx, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSortOrder", reflect.TypeOf((*MockHookRuleRepo)(nil).NextSortOrder), ctx, sourceID)
}

// Update mocks base method.
func (m *MockHookRuleRepo) Update(ctx context.Context, r *hook_entity.HookRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHookRuleRepoMockRecorder) Update(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHookRuleRepo)(nil).Update), ctx, r)
}

// MockHookEventRepo is a mock of HookEventRepo interface.
type MockHookEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHookEventRepoMockRecorder
	isgomock struct{}
}

// MockHookEventRepoMockRecorder is the mock recorder for MockHookEventRepo.
type MockHookEventRepoMockRecorder struct {
	mock *MockHookEventRepo
}

// NewMockHookEventRepo creates a new mock instance.
func NewMockHookEventRepo(ctrl *gomock.Controller) *MockHookEventRepo {
	mock := &MockHookEventRepo{ctrl: ctrl}
	mock.recorder = &MockHookEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookEventRepo) EXPECT() *MockHookEventRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHookEventRepo) Create(ctx context.Context, e *hook_entity.HookEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHookEventRepoMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHookEventRepo)(nil).Create), ctx, e)
}

// Find mocks base method.
func (m *MockHookEventRepo) Find(ctx context.Context, id int64) (*hook_entity.HookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*hook_entity.HookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockHookEventRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockHookEventRepo)(nil).Find), ctx, id)
}

// FindBySourceRef mocks base method.
func (m *MockHookEventRepo) FindBySourceRef(ctx context.Context, sourceID int64, sourceRef string) (*hook_entity.HookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySourceRef", ctx, sourceID, sourceRef)
	ret0, _ := ret[0].(*hook_entity.HookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySourceRef indicates an expected call of FindBySourceRef.
func (mr *MockHookEventRepoMockRecorder) FindBySourceRef(ctx, sourceID, sourceRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySourceRef", reflect.TypeOf((*MockHookEventRepo)(nil).FindBySourceRef), ctx, sourceID, sourceRef)
}

// ListBySource mocks base method.
func (m *MockHookEventRepo) ListBySource(ctx context.Context, sourceID int64, limit int) ([]*hook_entity.HookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySource", ctx, sourceID, limit)
	ret0, _ := ret[0].([]*hook_entity.HookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySource indicates an expected call of ListBySource.
func (mr *MockHookEventRepoMockRecorder) ListBySource(ctx, sourceID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySource", reflect.TypeOf((*MockHookEventRepo)(nil).ListBySource), ctx, sourceID, limit)
}

// ListRecent mocks base method.
func (m *MockHookEventRepo) ListRecent(ctx context.Context, limit int) ([]*hook_entity.HookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecent", ctx, limit)
	ret0, _ := ret[0].([]*hook_entity.HookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecent indicates an expected call of ListRecent.
func (mr *MockHookEventRepoMockRecorder) ListRecent(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecent", reflect.TypeOf((*MockHookEventRepo)(nil).ListRecent), ctx, limit)
}

// Update mocks base method.
func (m *MockHookEventRepo) Update(ctx context.Context, e *hook_entity.HookEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHookEventRepoMockRecorder) Update(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHookEventRepo)(nil).Update), ctx, e)
}
