// Code generated by MockGen. DO NOT EDIT.
// Source: project_agent.go
//
// Generated by this command:
//
//	mockgen -source project_agent.go -destination mock_project_repo/mock_project_agent.go
//

// Package mock_project_repo is a generated GoMock package.
package mock_project_repo

import (
	project_entity "agentre/internal/model/entity/project_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectAgentRepo is a mock of ProjectAgentRepo interface.
type MockProjectAgentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProjectAgentRepoMockRecorder
	isgomock struct{}
}

// MockProjectAgentRepoMockRecorder is the mock recorder for MockProjectAgentRepo.
type MockProjectAgentRepoMockRecorder struct {
	mock *MockProjectAgentRepo
}

// NewMockProjectAgentRepo creates a new mock instance.
func NewMockProjectAgentRepo(ctrl *gomock.Controller) *MockProjectAgentRepo {
	mock := &MockProjectAgentRepo{ctrl: ctrl}
	mock.recorder = &MockProjectAgentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectAgentRepo) EXPECT() *MockProjectAgentRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockProjectAgentRepo) Add(ctx context.Context, projectID, agentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, projectID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockProjectAgentRepoMockRecorder) Add(ctx, projectID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockProjectAgentRepo)(nil).Add), ctx, projectID, agentID)
}

// ListByAgent mocks base method.
func (m *MockProjectAgentRepo) ListByAgent(ctx context.Context, agentID int64) ([]*project_entity.ProjectAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgent", ctx, agentID)
	ret0, _ := ret[0].([]*project_entity.ProjectAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgent indicates an expected call of ListByAgent.
func (mr *MockProjectAgentRepoMockRecorder) ListByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgent", reflect.TypeOf((*MockProjectAgentRepo)(nil).ListByAgent), ctx, agentID)
}

// ListByProject mocks base method.
func (m *MockProjectAgentRepo) ListByProject(ctx context.Context, projectID int64) ([]*project_entity.ProjectAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID)
	ret0, _ := ret[0].([]*project_entity.ProjectAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockProjectAgentRepoMockRecorder) ListByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockProjectAgentRepo)(nil).ListByProject), ctx, projectID)
}

// ListByProjects mocks base method.
func (m *MockProjectAgentRepo) ListByProjects(ctx context.Context, projectIDs []int64) (map[int64][]*project_entity.ProjectAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProjects", ctx, projectIDs)
	ret0, _ := ret[0].(map[int64][]*project_entity.ProjectAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProjects indicates an expected call of ListByProjects.
func (mr *MockProjectAgentRepoMockRecorder) ListByProjects(ctx, projectIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProjects", reflect.TypeOf((*MockProjectAgentRepo)(nil).ListByProjects), ctx, projectIDs)
}

// Remove mocks base method.
func (m *MockProjectAgentRepo) Remove(ctx context.Context, projectID, agentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, projectID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockProjectAgentRepoMockRecorder) Remove(ctx, projectID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockProjectAgentRepo)(nil).Remove), ctx, projectID, agentID)
}
