// Code generated by MockGen. DO NOT EDIT.
// Source: project.go
//
// Generated by this command:
//
//	mockgen -source project.go -destination mock_project_repo/mock_project.go
//

// Package mock_project_repo is a generated GoMock package.
package mock_project_repo

import (
	project_entity "agentre/internal/model/entity/project_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepo is a mock of ProjectRepo interface.
type MockProjectRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepoMockRecorder
	isgomock struct{}
}

// MockProjectRepoMockRecorder is the mock recorder for MockProjectRepo.
type MockProjectRepoMockRecorder struct {
	mock *MockProjectRepo
}

// NewMockProjectRepo creates a new mock instance.
func NewMockProjectRepo(ctrl *gomock.Controller) *MockProjectRepo {
	mock := &MockProjectRepo{ctrl: ctrl}
	mock.recorder = &MockProjectRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepo) EXPECT() *MockProjectRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectRepo) Create(ctx context.Context, p *project_entity.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectRepo)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockProjectRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockProjectRepo) Find(ctx context.Context, id int64) (*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProjectRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProjectRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockProjectRepo) FindByName(ctx context.Context, parentID int64, name string) (*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, parentID, name)
	ret0, _ := ret[0].(*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockProjectRepoMockRecorder) FindByName(ctx, parentID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockProjectRepo)(nil).FindByName), ctx, parentID, name)
}

// HasActiveChildren mocks base method.
func (m *MockProjectRepo) HasActiveChildren(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveChildren", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveChildren indicates an expected call of HasActiveChildren.
func (mr *MockProjectRepoMockRecorder) HasActiveChildren(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveChildren", reflect.TypeOf((*MockProjectRepo)(nil).HasActiveChildren), ctx, id)
}

// List mocks base method.
func (m *MockProjectRepo) List(ctx context.Context) ([]*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectRepo)(nil).List), ctx)
}

// ListByParent mocks base method.
func (m *MockProjectRepo) ListByParent(ctx context.Context, parentID int64) ([]*project_entity.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByParent", ctx, parentID)
	ret0, _ := ret[0].([]*project_entity.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByParent indicates an expected call of ListByParent.
func (mr *MockProjectRepoMockRecorder) ListByParent(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByParent", reflect.TypeOf((*MockProjectRepo)(nil).ListByParent), ctx, parentID)
}

// Update mocks base method.
func (m *MockProjectRepo) Update(ctx context.Context, p *project_entity.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectRepoMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectRepo)(nil).Update), ctx, p)
}
