// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mock_workflowtool_svc/mock_deps.go
//

// Package mock_workflowtool_svc is a generated GoMock package.
package mock_workflowtool_svc

import (
	context "context"
	reflect "reflect"

	agent_entity "github.com/agentre-ai/agentre/internal/model/entity/agent_entity"
	blocks "github.com/agentre-ai/agentre/internal/service/chat_svc/blocks"
	workflow_svc "github.com/agentre-ai/agentre/internal/service/workflow_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowQuery is a mock of WorkflowQuery interface.
type MockWorkflowQuery struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowQueryMockRecorder
	isgomock struct{}
}

// MockWorkflowQueryMockRecorder is the mock recorder for MockWorkflowQuery.
type MockWorkflowQueryMockRecorder struct {
	mock *MockWorkflowQuery
}

// NewMockWorkflowQuery creates a new mock instance.
func NewMockWorkflowQuery(ctrl *gomock.Controller) *MockWorkflowQuery {
	mock := &MockWorkflowQuery{ctrl: ctrl}
	mock.recorder = &MockWorkflowQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowQuery) EXPECT() *MockWorkflowQueryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockWorkflowQuery) List(ctx context.Context, req *workflow_svc.ListWorkflowsRequest) (*workflow_svc.ListWorkflowsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*workflow_svc.ListWorkflowsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWorkflowQueryMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkflowQuery)(nil).List), ctx, req)
}

// MockWorkflowCommand is a mock of WorkflowCommand interface.
type MockWorkflowCommand struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowCommandMockRecorder
	isgomock struct{}
}

// MockWorkflowCommandMockRecorder is the mock recorder for MockWorkflowCommand.
type MockWorkflowCommandMockRecorder struct {
	mock *MockWorkflowCommand
}

// NewMockWorkflowCommand creates a new mock instance.
func NewMockWorkflowCommand(ctrl *gomock.Controller) *MockWorkflowCommand {
	mock := &MockWorkflowCommand{ctrl: ctrl}
	mock.recorder = &MockWorkflowCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowCommand) EXPECT() *MockWorkflowCommandMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkflowCommand) Create(ctx context.Context, req *workflow_svc.CreateWorkflowRequest) (*workflow_svc.CreateWorkflowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*workflow_svc.CreateWorkflowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkflowCommandMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkflowCommand)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockWorkflowCommand) Delete(ctx context.Context, req *workflow_svc.DeleteWorkflowRequest) (*workflow_svc.DeleteWorkflowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*workflow_svc.DeleteWorkflowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkflowCommandMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowCommand)(nil).Delete), ctx, req)
}

// Update mocks base method.
func (m *MockWorkflowCommand) Update(ctx context.Context, req *workflow_svc.UpdateWorkflowRequest) (*workflow_svc.UpdateWorkflowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*workflow_svc.UpdateWorkflowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWorkflowCommandMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowCommand)(nil).Update), ctx, req)
}

// MockAgentLookup is a mock of AgentLookup interface.
type MockAgentLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAgentLookupMockRecorder
	isgomock struct{}
}

// MockAgentLookupMockRecorder is the mock recorder for MockAgentLookup.
type MockAgentLookupMockRecorder struct {
	mock *MockAgentLookup
}

// NewMockAgentLookup creates a new mock instance.
func NewMockAgentLookup(ctrl *gomock.Controller) *MockAgentLookup {
	mock := &MockAgentLookup{ctrl: ctrl}
	mock.recorder = &MockAgentLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentLookup) EXPECT() *MockAgentLookupMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentLookup) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentLookupMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentLookup)(nil).Find), ctx, id)
}

// MockApprovalGateway is a mock of ApprovalGateway interface.
type MockApprovalGateway struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalGatewayMockRecorder
	isgomock struct{}
}

// MockApprovalGatewayMockRecorder is the mock recorder for MockApprovalGateway.
type MockApprovalGatewayMockRecorder struct {
	mock *MockApprovalGateway
}

// NewMockApprovalGateway creates a new mock instance.
func NewMockApprovalGateway(ctrl *gomock.Controller) *MockApprovalGateway {
	mock := &MockApprovalGateway{ctrl: ctrl}
	mock.recorder = &MockApprovalGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalGateway) EXPECT() *MockApprovalGatewayMockRecorder {
	return m.recorder
}

// BeginToolApproval mocks base method.
func (m *MockApprovalGateway) BeginToolApproval(ctx context.Context, sessionID int64, blk *blocks.ToolApprovalBlock) (<-chan bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginToolApproval", ctx, sessionID, blk)
	ret0, _ := ret[0].(<-chan bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginToolApproval indicates an expected call of BeginToolApproval.
func (mr *MockApprovalGatewayMockRecorder) BeginToolApproval(ctx, sessionID, blk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginToolApproval", reflect.TypeOf((*MockApprovalGateway)(nil).BeginToolApproval), ctx, sessionID, blk)
}

// FinishToolApproval mocks base method.
func (m *MockApprovalGateway) FinishToolApproval(ctx context.Context, sessionID int64, requestID, status, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishToolApproval", ctx, sessionID, requestID, status, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishToolApproval indicates an expected call of FinishToolApproval.
func (mr *MockApprovalGatewayMockRecorder) FinishToolApproval(ctx, sessionID, requestID, status, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishToolApproval", reflect.TypeOf((*MockApprovalGateway)(nil).FinishToolApproval), ctx, sessionID, requestID, status, result)
}
