// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_agentruntime/mock_ports.go
//

// Package mock_agentruntime is a generated GoMock package.
package mock_agentruntime

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDaemonClientPort is a mock of DaemonClientPort interface.
type MockDaemonClientPort struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonClientPortMockRecorder
	isgomock struct{}
}

// MockDaemonClientPortMockRecorder is the mock recorder for MockDaemonClientPort.
type MockDaemonClientPortMockRecorder struct {
	mock *MockDaemonClientPort
}

// NewMockDaemonClientPort creates a new mock instance.
func NewMockDaemonClientPort(ctrl *gomock.Controller) *MockDaemonClientPort {
	mock := &MockDaemonClientPort{ctrl: ctrl}
	mock.recorder = &MockDaemonClientPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemonClientPort) EXPECT() *MockDaemonClientPortMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockDaemonClientPort) Call(ctx context.Context, method string, params, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, method, params, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockDaemonClientPortMockRecorder) Call(ctx, method, params, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockDaemonClientPort)(nil).Call), ctx, method, params, result)
}

// Close mocks base method.
func (m *MockDaemonClientPort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDaemonClientPortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDaemonClientPort)(nil).Close))
}

// Closed mocks base method.
func (m *MockDaemonClientPort) Closed() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Closed")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Closed indicates an expected call of Closed.
func (mr *MockDaemonClientPortMockRecorder) Closed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Closed", reflect.TypeOf((*MockDaemonClientPort)(nil).Closed))
}

// Handle mocks base method.
func (m *MockDaemonClientPort) Handle(method string, fn func(context.Context, json.RawMessage) (any, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", method, fn)
}

// Handle indicates an expected call of Handle.
func (mr *MockDaemonClientPortMockRecorder) Handle(method, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockDaemonClientPort)(nil).Handle), method, fn)
}

// Notify mocks base method.
func (m *MockDaemonClientPort) Notify(method string, params any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", method, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockDaemonClientPortMockRecorder) Notify(method, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockDaemonClientPort)(nil).Notify), method, params)
}
