// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source runner.go -destination mock_agentruntime/mock_runner.go
//

// Package mock_agentruntime is a generated GoMock package.
package mock_agentruntime

import (
	context "context"
	agentruntime "github.com/agentre-ai/agentre/internal/pkg/agentruntime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockToolPermissionSink is a mock of ToolPermissionSink interface.
type MockToolPermissionSink struct {
	ctrl     *gomock.Controller
	recorder *MockToolPermissionSinkMockRecorder
	isgomock struct{}
}

// MockToolPermissionSinkMockRecorder is the mock recorder for MockToolPermissionSink.
type MockToolPermissionSinkMockRecorder struct {
	mock *MockToolPermissionSink
}

// NewMockToolPermissionSink creates a new mock instance.
func NewMockToolPermissionSink(ctrl *gomock.Controller) *MockToolPermissionSink {
	mock := &MockToolPermissionSink{ctrl: ctrl}
	mock.recorder = &MockToolPermissionSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolPermissionSink) EXPECT() *MockToolPermissionSinkMockRecorder {
	return m.recorder
}

// SubmitToolPermission mocks base method.
func (m *MockToolPermissionSink) SubmitToolPermission(ctx context.Context, sessionID int64, requestID string, allow, alwaysAllowSession bool, denyReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitToolPermission", ctx, sessionID, requestID, allow, alwaysAllowSession, denyReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitToolPermission indicates an expected call of SubmitToolPermission.
func (mr *MockToolPermissionSinkMockRecorder) SubmitToolPermission(ctx, sessionID, requestID, allow, alwaysAllowSession, denyReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitToolPermission", reflect.TypeOf((*MockToolPermissionSink)(nil).SubmitToolPermission), ctx, sessionID, requestID, allow, alwaysAllowSession, denyReason)
}

// MockAskAnswerSink is a mock of AskAnswerSink interface.
type MockAskAnswerSink struct {
	ctrl     *gomock.Controller
	recorder *MockAskAnswerSinkMockRecorder
	isgomock struct{}
}

// MockAskAnswerSinkMockRecorder is the mock recorder for MockAskAnswerSink.
type MockAskAnswerSinkMockRecorder struct {
	mock *MockAskAnswerSink
}

// NewMockAskAnswerSink creates a new mock instance.
func NewMockAskAnswerSink(ctrl *gomock.Controller) *MockAskAnswerSink {
	mock := &MockAskAnswerSink{ctrl: ctrl}
	mock.recorder = &MockAskAnswerSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAskAnswerSink) EXPECT() *MockAskAnswerSinkMockRecorder {
	return m.recorder
}

// SubmitAnswer mocks base method.
func (m *MockAskAnswerSink) SubmitAnswer(ctx context.Context, sessionID int64, requestID string, questions []agentruntime.AskQuestion, answers []agentruntime.AskAnswer, skipped bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitAnswer", ctx, sessionID, requestID, questions, answers, skipped)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitAnswer indicates an expected call of SubmitAnswer.
func (mr *MockAskAnswerSinkMockRecorder) SubmitAnswer(ctx, sessionID, requestID, questions, answers, skipped any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAnswer", reflect.TypeOf((*MockAskAnswerSink)(nil).SubmitAnswer), ctx, sessionID, requestID, questions, answers, skipped)
}

// MockSteerer is a mock of Steerer interface.
type MockSteerer struct {
	ctrl     *gomock.Controller
	recorder *MockSteererMockRecorder
	isgomock struct{}
}

// MockSteererMockRecorder is the mock recorder for MockSteerer.
type MockSteererMockRecorder struct {
	mock *MockSteerer
}

// NewMockSteerer creates a new mock instance.
func NewMockSteerer(ctrl *gomock.Controller) *MockSteerer {
	mock := &MockSteerer{ctrl: ctrl}
	mock.recorder = &MockSteererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSteerer) EXPECT() *MockSteererMockRecorder {
	return m.recorder
}

// Steer mocks base method.
func (m *MockSteerer) Steer(ctx context.Context, sessionID int64, queuedID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Steer", ctx, sessionID, queuedID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Steer indicates an expected call of Steer.
func (mr *MockSteererMockRecorder) Steer(ctx, sessionID, queuedID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Steer", reflect.TypeOf((*MockSteerer)(nil).Steer), ctx, sessionID, queuedID, text)
}

// MockSteerCanceler is a mock of SteerCanceler interface.
type MockSteerCanceler struct {
	ctrl     *gomock.Controller
	recorder *MockSteerCancelerMockRecorder
	isgomock struct{}
}

// MockSteerCancelerMockRecorder is the mock recorder for MockSteerCanceler.
type MockSteerCancelerMockRecorder struct {
	mock *MockSteerCanceler
}

// NewMockSteerCanceler creates a new mock instance.
func NewMockSteerCanceler(ctrl *gomock.Controller) *MockSteerCanceler {
	mock := &MockSteerCanceler{ctrl: ctrl}
	mock.recorder = &MockSteerCancelerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSteerCanceler) EXPECT() *MockSteerCancelerMockRecorder {
	return m.recorder
}

// CancelSteer mocks base method.
func (m *MockSteerCanceler) CancelSteer(ctx context.Context, sessionID int64, queuedID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSteer", ctx, sessionID, queuedID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelSteer indicates an expected call of CancelSteer.
func (mr *MockSteerCancelerMockRecorder) CancelSteer(ctx, sessionID, queuedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSteer", reflect.TypeOf((*MockSteerCanceler)(nil).CancelSteer), ctx, sessionID, queuedID)
}

// MockSteerDrainer is a mock of SteerDrainer interface.
type MockSteerDrainer struct {
	ctrl     *gomock.Controller
	recorder *MockSteerDrainerMockRecorder
	isgomock struct{}
}

// MockSteerDrainerMockRecorder is the mock recorder for MockSteerDrainer.
type MockSteerDrainerMockRecorder struct {
	mock *MockSteerDrainer
}

// NewMockSteerDrainer creates a new mock instance.
func NewMockSteerDrainer(ctrl *gomock.Controller) *MockSteerDrainer {
	mock := &MockSteerDrainer{ctrl: ctrl}
	mock.recorder = &MockSteerDrainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSteerDrainer) EXPECT() *MockSteerDrainerMockRecorder {
	return m.recorder
}

// DrainPending mocks base method.
func (m *MockSteerDrainer) DrainPending(ctx context.Context, sessionID int64) []agentruntime.ConsumedSteer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainPending", ctx, sessionID)
	ret0, _ := ret[0].([]agentruntime.ConsumedSteer)
	return ret0
}

// DrainPending indicates an expected call of DrainPending.
func (mr *MockSteerDrainerMockRecorder) DrainPending(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainPending", reflect.TypeOf((*MockSteerDrainer)(nil).DrainPending), ctx, sessionID)
}

// MockAborter is a mock of Aborter interface.
type MockAborter struct {
	ctrl     *gomock.Controller
	recorder *MockAborterMockRecorder
	isgomock struct{}
}

// MockAborterMockRecorder is the mock recorder for MockAborter.
type MockAborterMockRecorder struct {
	mock *MockAborter
}

// NewMockAborter creates a new mock instance.
func NewMockAborter(ctrl *gomock.Controller) *MockAborter {
	mock := &MockAborter{ctrl: ctrl}
	mock.recorder = &MockAborterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAborter) EXPECT() *MockAborterMockRecorder {
	return m.recorder
}

// Abort mocks base method.
func (m *MockAborter) Abort(ctx context.Context, sessionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abort", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Abort indicates an expected call of Abort.
func (mr *MockAborterMockRecorder) Abort(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abort", reflect.TypeOf((*MockAborter)(nil).Abort), ctx, sessionID)
}

// MockPermissionModeSetter is a mock of PermissionModeSetter interface.
type MockPermissionModeSetter struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionModeSetterMockRecorder
	isgomock struct{}
}

// MockPermissionModeSetterMockRecorder is the mock recorder for MockPermissionModeSetter.
type MockPermissionModeSetterMockRecorder struct {
	mock *MockPermissionModeSetter
}

// NewMockPermissionModeSetter creates a new mock instance.
func NewMockPermissionModeSetter(ctrl *gomock.Controller) *MockPermissionModeSetter {
	mock := &MockPermissionModeSetter{ctrl: ctrl}
	mock.recorder = &MockPermissionModeSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionModeSetter) EXPECT() *MockPermissionModeSetterMockRecorder {
	return m.recorder
}

// SetPermissionMode mocks base method.
func (m *MockPermissionModeSetter) SetPermissionMode(ctx context.Context, sessionID int64, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPermissionMode", ctx, sessionID, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPermissionMode indicates an expected call of SetPermissionMode.
func (mr *MockPermissionModeSetterMockRecorder) SetPermissionMode(ctx, sessionID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPermissionMode", reflect.TypeOf((*MockPermissionModeSetter)(nil).SetPermissionMode), ctx, sessionID, mode)
}

// MockAutonomousTurnSource is a mock of AutonomousTurnSource interface.
type MockAutonomousTurnSource struct {
	ctrl     *gomock.Controller
	recorder *MockAutonomousTurnSourceMockRecorder
	isgomock struct{}
}

// MockAutonomousTurnSourceMockRecorder is the mock recorder for MockAutonomousTurnSource.
type MockAutonomousTurnSourceMockRecorder struct {
	mock *MockAutonomousTurnSource
}

// NewMockAutonomousTurnSource creates a new mock instance.
func NewMockAutonomousTurnSource(ctrl *gomock.Controller) *MockAutonomousTurnSource {
	mock := &MockAutonomousTurnSource{ctrl: ctrl}
	mock.recorder = &MockAutonomousTurnSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutonomousTurnSource) EXPECT() *MockAutonomousTurnSourceMockRecorder {
	return m.recorder
}

// AutonomousTurns mocks base method.
func (m *MockAutonomousTurnSource) AutonomousTurns(sessionID int64) <-chan agentruntime.AutonomousTurn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutonomousTurns", sessionID)
	ret0, _ := ret[0].(<-chan agentruntime.AutonomousTurn)
	return ret0
}

// AutonomousTurns indicates an expected call of AutonomousTurns.
func (mr *MockAutonomousTurnSourceMockRecorder) AutonomousTurns(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutonomousTurns", reflect.TypeOf((*MockAutonomousTurnSource)(nil).AutonomousTurns), sessionID)
}
