// Code generated by MockGen. DO NOT EDIT.
// Source: group.go
//
// Generated by this command:
//
//	mockgen -source group.go -destination mock_group_repo/mock_group.go
//

// Package mock_group_repo is a generated GoMock package.
package mock_group_repo

import (
	context "context"
	group_entity "github.com/agentre-ai/agentre/internal/model/entity/group_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGroupRepo is a mock of GroupRepo interface.
type MockGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepoMockRecorder
	isgomock struct{}
}

// MockGroupRepoMockRecorder is the mock recorder for MockGroupRepo.
type MockGroupRepoMockRecorder struct {
	mock *MockGroupRepo
}

// NewMockGroupRepo creates a new mock instance.
func NewMockGroupRepo(ctrl *gomock.Controller) *MockGroupRepo {
	mock := &MockGroupRepo{ctrl: ctrl}
	mock.recorder = &MockGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepo) EXPECT() *MockGroupRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupRepo) Create(ctx context.Context, g *group_entity.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupRepoMockRecorder) Create(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupRepo)(nil).Create), ctx, g)
}

// Find mocks base method.
func (m *MockGroupRepo) Find(ctx context.Context, id int64) (*group_entity.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*group_entity.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockGroupRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockGroupRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockGroupRepo) List(ctx context.Context) ([]*group_entity.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*group_entity.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGroupRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupRepo)(nil).List), ctx)
}

// SetPinned mocks base method.
func (m *MockGroupRepo) SetPinned(ctx context.Context, id int64, pinned bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPinned", ctx, id, pinned)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPinned indicates an expected call of SetPinned.
func (mr *MockGroupRepoMockRecorder) SetPinned(ctx, id, pinned any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPinned", reflect.TypeOf((*MockGroupRepo)(nil).SetPinned), ctx, id, pinned)
}

// Update mocks base method.
func (m *MockGroupRepo) Update(ctx context.Context, g *group_entity.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupRepoMockRecorder) Update(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupRepo)(nil).Update), ctx, g)
}

// MockGroupMemberRepo is a mock of GroupMemberRepo interface.
type MockGroupMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupMemberRepoMockRecorder
	isgomock struct{}
}

// MockGroupMemberRepoMockRecorder is the mock recorder for MockGroupMemberRepo.
type MockGroupMemberRepoMockRecorder struct {
	mock *MockGroupMemberRepo
}

// NewMockGroupMemberRepo creates a new mock instance.
func NewMockGroupMemberRepo(ctrl *gomock.Controller) *MockGroupMemberRepo {
	mock := &MockGroupMemberRepo{ctrl: ctrl}
	mock.recorder = &MockGroupMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupMemberRepo) EXPECT() *MockGroupMemberRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockGroupMemberRepo) Create(ctx context.Context, m *group_entity.GroupMember) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupMemberRepoMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupMemberRepo)(nil).Create), ctx, m)
}

// Find mocks base method.
func (m *MockGroupMemberRepo) Find(ctx context.Context, id int64) (*group_entity.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*group_entity.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockGroupMemberRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockGroupMemberRepo)(nil).Find), ctx, id)
}

// FindByGroupAndAgent mocks base method.
func (m *MockGroupMemberRepo) FindByGroupAndAgent(ctx context.Context, groupID, agentID int64) (*group_entity.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGroupAndAgent", ctx, groupID, agentID)
	ret0, _ := ret[0].(*group_entity.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGroupAndAgent indicates an expected call of FindByGroupAndAgent.
func (mr *MockGroupMemberRepoMockRecorder) FindByGroupAndAgent(ctx, groupID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGroupAndAgent", reflect.TypeOf((*MockGroupMemberRepo)(nil).FindByGroupAndAgent), ctx, groupID, agentID)
}

// ListByGroup mocks base method.
func (m *MockGroupMemberRepo) ListByGroup(ctx context.Context, groupID int64) ([]*group_entity.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGroup", ctx, groupID)
	ret0, _ := ret[0].([]*group_entity.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGroup indicates an expected call of ListByGroup.
func (mr *MockGroupMemberRepoMockRecorder) ListByGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGroup", reflect.TypeOf((*MockGroupMemberRepo)(nil).ListByGroup), ctx, groupID)
}

// Update mocks base method.
func (m_2 *MockGroupMemberRepo) Update(ctx context.Context, m *group_entity.GroupMember) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupMemberRepoMockRecorder) Update(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupMemberRepo)(nil).Update), ctx, m)
}

// MockGroupMessageRepo is a mock of GroupMessageRepo interface.
type MockGroupMessageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupMessageRepoMockRecorder
	isgomock struct{}
}

// MockGroupMessageRepoMockRecorder is the mock recorder for MockGroupMessageRepo.
type MockGroupMessageRepoMockRecorder struct {
	mock *MockGroupMessageRepo
}

// NewMockGroupMessageRepo creates a new mock instance.
func NewMockGroupMessageRepo(ctrl *gomock.Controller) *MockGroupMessageRepo {
	mock := &MockGroupMessageRepo{ctrl: ctrl}
	mock.recorder = &MockGroupMessageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupMessageRepo) EXPECT() *MockGroupMessageRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockGroupMessageRepo) Create(ctx context.Context, m *group_entity.GroupMessage) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupMessageRepoMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupMessageRepo)(nil).Create), ctx, m)
}

// ListByGroup mocks base method.
func (m *MockGroupMessageRepo) ListByGroup(ctx context.Context, groupID int64) ([]*group_entity.GroupMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGroup", ctx, groupID)
	ret0, _ := ret[0].([]*group_entity.GroupMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGroup indicates an expected call of ListByGroup.
func (mr *MockGroupMessageRepoMockRecorder) ListByGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGroup", reflect.TypeOf((*MockGroupMessageRepo)(nil).ListByGroup), ctx, groupID)
}

// NextSeq mocks base method.
func (m *MockGroupMessageRepo) NextSeq(ctx context.Context, groupID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSeq", ctx, groupID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSeq indicates an expected call of NextSeq.
func (mr *MockGroupMessageRepoMockRecorder) NextSeq(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSeq", reflect.TypeOf((*MockGroupMessageRepo)(nil).NextSeq), ctx, groupID)
}
