// Code generated by MockGen. DO NOT EDIT.
// Source: task.go
//
// Generated by this command:
//
//	mockgen -source task.go -destination mock_group_repo/mock_task.go
//

// Package mock_group_repo is a generated GoMock package.
package mock_group_repo

import (
	context "context"
	reflect "reflect"

	group_entity "github.com/agentre-ai/agentre/internal/model/entity/group_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupTaskRepo is a mock of GroupTaskRepo interface.
type MockGroupTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupTaskRepoMockRecorder
	isgomock struct{}
}

// MockGroupTaskRepoMockRecorder is the mock recorder for MockGroupTaskRepo.
type MockGroupTaskRepoMockRecorder struct {
	mock *MockGroupTaskRepo
}

// NewMockGroupTaskRepo creates a new mock instance.
func NewMockGroupTaskRepo(ctrl *gomock.Controller) *MockGroupTaskRepo {
	mock := &MockGroupTaskRepo{ctrl: ctrl}
	mock.recorder = &MockGroupTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupTaskRepo) EXPECT() *MockGroupTaskRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupTaskRepo) Create(ctx context.Context, t *group_entity.GroupTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupTaskRepoMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupTaskRepo)(nil).Create), ctx, t)
}

// FindByGroupAndNo mocks base method.
func (m *MockGroupTaskRepo) FindByGroupAndNo(ctx context.Context, groupID int64, taskNo int) (*group_entity.GroupTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGroupAndNo", ctx, groupID, taskNo)
	ret0, _ := ret[0].(*group_entity.GroupTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGroupAndNo indicates an expected call of FindByGroupAndNo.
func (mr *MockGroupTaskRepoMockRecorder) FindByGroupAndNo(ctx, groupID, taskNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGroupAndNo", reflect.TypeOf((*MockGroupTaskRepo)(nil).FindByGroupAndNo), ctx, groupID, taskNo)
}

// ListByGroup mocks base method.
func (m *MockGroupTaskRepo) ListByGroup(ctx context.Context, groupID int64) ([]*group_entity.GroupTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGroup", ctx, groupID)
	ret0, _ := ret[0].([]*group_entity.GroupTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGroup indicates an expected call of ListByGroup.
func (mr *MockGroupTaskRepoMockRecorder) ListByGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGroup", reflect.TypeOf((*MockGroupTaskRepo)(nil).ListByGroup), ctx, groupID)
}

// NextTaskNo mocks base method.
func (m *MockGroupTaskRepo) NextTaskNo(ctx context.Context, groupID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextTaskNo", ctx, groupID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextTaskNo indicates an expected call of NextTaskNo.
func (mr *MockGroupTaskRepoMockRecorder) NextTaskNo(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextTaskNo", reflect.TypeOf((*MockGroupTaskRepo)(nil).NextTaskNo), ctx, groupID)
}

// Update mocks base method.
func (m *MockGroupTaskRepo) Update(ctx context.Context, t *group_entity.GroupTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupTaskRepoMockRecorder) Update(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupTaskRepo)(nil).Update), ctx, t)
}
