// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source service.go -destination mock_update_svc/mock_service.go
//

// Package mock_update_svc is a generated GoMock package.
package mock_update_svc

import (
	context "context"
	update_svc "github.com/agentre-ai/agentre/internal/service/update_svc"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CheckForUpdate mocks base method.
func (m *MockService) CheckForUpdate(channel, mirrorPrefix string) (*update_svc.UpdateInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForUpdate", channel, mirrorPrefix)
	ret0, _ := ret[0].(*update_svc.UpdateInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForUpdate indicates an expected call of CheckForUpdate.
func (mr *MockServiceMockRecorder) CheckForUpdate(channel, mirrorPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForUpdate", reflect.TypeOf((*MockService)(nil).CheckForUpdate), channel, mirrorPrefix)
}

// DownloadAndUpdate mocks base method.
func (m *MockService) DownloadAndUpdate(channel, mirrorPrefix string, skipChecksum bool, onProgress func(int64, int64)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadAndUpdate", channel, mirrorPrefix, skipChecksum, onProgress)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadAndUpdate indicates an expected call of DownloadAndUpdate.
func (mr *MockServiceMockRecorder) DownloadAndUpdate(channel, mirrorPrefix, skipChecksum, onProgress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadAndUpdate", reflect.TypeOf((*MockService)(nil).DownloadAndUpdate), channel, mirrorPrefix, skipChecksum, onProgress)
}

// GetAvailableMirrors mocks base method.
func (m *MockService) GetAvailableMirrors() []update_svc.MirrorInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableMirrors")
	ret0, _ := ret[0].([]update_svc.MirrorInfo)
	return ret0
}

// GetAvailableMirrors indicates an expected call of GetAvailableMirrors.
func (mr *MockServiceMockRecorder) GetAvailableMirrors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableMirrors", reflect.TypeOf((*MockService)(nil).GetAvailableMirrors))
}

// GetChannel mocks base method.
func (m *MockService) GetChannel(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockServiceMockRecorder) GetChannel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockService)(nil).GetChannel), ctx)
}

// GetLastUpdateCheck mocks base method.
func (m *MockService) GetLastUpdateCheck(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUpdateCheck", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUpdateCheck indicates an expected call of GetLastUpdateCheck.
func (mr *MockServiceMockRecorder) GetLastUpdateCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUpdateCheck", reflect.TypeOf((*MockService)(nil).GetLastUpdateCheck), ctx)
}

// GetMirror mocks base method.
func (m *MockService) GetMirror(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMirror", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMirror indicates an expected call of GetMirror.
func (mr *MockServiceMockRecorder) GetMirror(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMirror", reflect.TypeOf((*MockService)(nil).GetMirror), ctx)
}

// SetChannel mocks base method.
func (m *MockService) SetChannel(ctx context.Context, channel string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChannel", ctx, channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetChannel indicates an expected call of SetChannel.
func (mr *MockServiceMockRecorder) SetChannel(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChannel", reflect.TypeOf((*MockService)(nil).SetChannel), ctx, channel)
}

// SetLastUpdateCheck mocks base method.
func (m *MockService) SetLastUpdateCheck(ctx context.Context, ts int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastUpdateCheck", ctx, ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastUpdateCheck indicates an expected call of SetLastUpdateCheck.
func (mr *MockServiceMockRecorder) SetLastUpdateCheck(ctx, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastUpdateCheck", reflect.TypeOf((*MockService)(nil).SetLastUpdateCheck), ctx, ts)
}

// SetMirror mocks base method.
func (m *MockService) SetMirror(ctx context.Context, mirror string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMirror", ctx, mirror)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMirror indicates an expected call of SetMirror.
func (mr *MockServiceMockRecorder) SetMirror(ctx, mirror any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMirror", reflect.TypeOf((*MockService)(nil).SetMirror), ctx, mirror)
}
