// Code generated by MockGen. DO NOT EDIT.
// Source: message.go
//
// Generated by this command:
//
//	mockgen -source message.go -destination mock_chat_repo/mock_message.go
//

// Package mock_chat_repo is a generated GoMock package.
package mock_chat_repo

import (
	context "context"
	reflect "reflect"

	chat_entity "github.com/agentre-ai/agentre/internal/model/entity/chat_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepo is a mock of MessageRepo interface.
type MockMessageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepoMockRecorder
	isgomock struct{}
}

// MockMessageRepoMockRecorder is the mock recorder for MockMessageRepo.
type MockMessageRepoMockRecorder struct {
	mock *MockMessageRepo
}

// NewMockMessageRepo creates a new mock instance.
func NewMockMessageRepo(ctrl *gomock.Controller) *MockMessageRepo {
	mock := &MockMessageRepo{ctrl: ctrl}
	mock.recorder = &MockMessageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepo) EXPECT() *MockMessageRepoMockRecorder {
	return m.recorder
}

// AppendSubagentChildren mocks base method.
func (m *MockMessageRepo) AppendSubagentChildren(ctx context.Context, sessionID int64, parentToolUseID, childBlocksJSON string, childIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendSubagentChildren", ctx, sessionID, parentToolUseID, childBlocksJSON, childIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendSubagentChildren indicates an expected call of AppendSubagentChildren.
func (mr *MockMessageRepoMockRecorder) AppendSubagentChildren(ctx, sessionID, parentToolUseID, childBlocksJSON, childIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendSubagentChildren", reflect.TypeOf((*MockMessageRepo)(nil).AppendSubagentChildren), ctx, sessionID, parentToolUseID, childBlocksJSON, childIDs)
}

// Create mocks base method.
func (m_2 *MockMessageRepo) Create(ctx context.Context, m *chat_entity.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessageRepoMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageRepo)(nil).Create), ctx, m)
}

// DeleteFromSeq mocks base method.
func (m *MockMessageRepo) DeleteFromSeq(ctx context.Context, sessionID int64, fromSeq int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFromSeq", ctx, sessionID, fromSeq)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFromSeq indicates an expected call of DeleteFromSeq.
func (mr *MockMessageRepoMockRecorder) DeleteFromSeq(ctx, sessionID, fromSeq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFromSeq", reflect.TypeOf((*MockMessageRepo)(nil).DeleteFromSeq), ctx, sessionID, fromSeq)
}

// Find mocks base method.
func (m *MockMessageRepo) Find(ctx context.Context, id int64) (*chat_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*chat_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMessageRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMessageRepo)(nil).Find), ctx, id)
}

// FindAssistantBySubagentToolUseID mocks base method.
func (m *MockMessageRepo) FindAssistantBySubagentToolUseID(ctx context.Context, sessionID int64, toolUseID string) (*chat_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAssistantBySubagentToolUseID", ctx, sessionID, toolUseID)
	ret0, _ := ret[0].(*chat_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAssistantBySubagentToolUseID indicates an expected call of FindAssistantBySubagentToolUseID.
func (mr *MockMessageRepoMockRecorder) FindAssistantBySubagentToolUseID(ctx, sessionID, toolUseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAssistantBySubagentToolUseID", reflect.TypeOf((*MockMessageRepo)(nil).FindAssistantBySubagentToolUseID), ctx, sessionID, toolUseID)
}

// FlipSubagentStatus mocks base method.
func (m *MockMessageRepo) FlipSubagentStatus(ctx context.Context, sessionID int64, toolUseID, status, summary string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlipSubagentStatus", ctx, sessionID, toolUseID, status, summary)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlipSubagentStatus indicates an expected call of FlipSubagentStatus.
func (mr *MockMessageRepoMockRecorder) FlipSubagentStatus(ctx, sessionID, toolUseID, status, summary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlipSubagentStatus", reflect.TypeOf((*MockMessageRepo)(nil).FlipSubagentStatus), ctx, sessionID, toolUseID, status, summary)
}

// List mocks base method.
func (m *MockMessageRepo) List(ctx context.Context, sessionID int64) ([]*chat_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, sessionID)
	ret0, _ := ret[0].([]*chat_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMessageRepoMockRecorder) List(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMessageRepo)(nil).List), ctx, sessionID)
}

// NextSeq mocks base method.
func (m *MockMessageRepo) NextSeq(ctx context.Context, sessionID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSeq", ctx, sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSeq indicates an expected call of NextSeq.
func (mr *MockMessageRepoMockRecorder) NextSeq(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSeq", reflect.TypeOf((*MockMessageRepo)(nil).NextSeq), ctx, sessionID)
}

// Update mocks base method.
func (m_2 *MockMessageRepo) Update(ctx context.Context, m *chat_entity.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMessageRepoMockRecorder) Update(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageRepo)(nil).Update), ctx, m)
}
