// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -source session.go -destination mock_chat_repo/mock_session.go
//

// Package mock_chat_repo is a generated GoMock package.
package mock_chat_repo

import (
	chat_entity "agentre/internal/model/entity/chat_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepo is a mock of SessionRepo interface.
type MockSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepoMockRecorder
	isgomock struct{}
}

// MockSessionRepoMockRecorder is the mock recorder for MockSessionRepo.
type MockSessionRepoMockRecorder struct {
	mock *MockSessionRepo
}

// NewMockSessionRepo creates a new mock instance.
func NewMockSessionRepo(ctrl *gomock.Controller) *MockSessionRepo {
	mock := &MockSessionRepo{ctrl: ctrl}
	mock.recorder = &MockSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepo) EXPECT() *MockSessionRepoMockRecorder {
	return m.recorder
}

// CountActive mocks base method.
func (m *MockSessionRepo) CountActive(ctx context.Context, agentStatuses []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive", ctx, agentStatuses)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockSessionRepoMockRecorder) CountActive(ctx, agentStatuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockSessionRepo)(nil).CountActive), ctx, agentStatuses)
}

// CountActiveByProject mocks base method.
func (m *MockSessionRepo) CountActiveByProject(ctx context.Context, projectID int64, agentStatuses []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByProject", ctx, projectID, agentStatuses)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByProject indicates an expected call of CountActiveByProject.
func (mr *MockSessionRepoMockRecorder) CountActiveByProject(ctx, projectID, agentStatuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByProject", reflect.TypeOf((*MockSessionRepo)(nil).CountActiveByProject), ctx, projectID, agentStatuses)
}

// CountByAgent mocks base method.
func (m *MockSessionRepo) CountByAgent(ctx context.Context, agentID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByAgent", ctx, agentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByAgent indicates an expected call of CountByAgent.
func (mr *MockSessionRepoMockRecorder) CountByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByAgent", reflect.TypeOf((*MockSessionRepo)(nil).CountByAgent), ctx, agentID)
}

// CountByAgents mocks base method.
func (m *MockSessionRepo) CountByAgents(ctx context.Context, agentIDs []int64) (map[int64]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByAgents", ctx, agentIDs)
	ret0, _ := ret[0].(map[int64]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByAgents indicates an expected call of CountByAgents.
func (mr *MockSessionRepoMockRecorder) CountByAgents(ctx, agentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByAgents", reflect.TypeOf((*MockSessionRepo)(nil).CountByAgents), ctx, agentIDs)
}

// CountRunningByAgents mocks base method.
func (m *MockSessionRepo) CountRunningByAgents(ctx context.Context, agentIDs []int64) (map[int64]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRunningByAgents", ctx, agentIDs)
	ret0, _ := ret[0].(map[int64]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRunningByAgents indicates an expected call of CountRunningByAgents.
func (mr *MockSessionRepoMockRecorder) CountRunningByAgents(ctx, agentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRunningByAgents", reflect.TypeOf((*MockSessionRepo)(nil).CountRunningByAgents), ctx, agentIDs)
}

// Create mocks base method.
func (m *MockSessionRepo) Create(ctx context.Context, s *chat_entity.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepoMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepo)(nil).Create), ctx, s)
}

// Find mocks base method.
func (m *MockSessionRepo) Find(ctx context.Context, id int64) (*chat_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*chat_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSessionRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSessionRepo)(nil).Find), ctx, id)
}

// ListAttentionByAgent mocks base method.
func (m *MockSessionRepo) ListAttentionByAgent(ctx context.Context, agentID int64, limit int) ([]*chat_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttentionByAgent", ctx, agentID, limit)
	ret0, _ := ret[0].([]*chat_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttentionByAgent indicates an expected call of ListAttentionByAgent.
func (mr *MockSessionRepoMockRecorder) ListAttentionByAgent(ctx, agentID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttentionByAgent", reflect.TypeOf((*MockSessionRepo)(nil).ListAttentionByAgent), ctx, agentID, limit)
}

// ListByAgent mocks base method.
func (m *MockSessionRepo) ListByAgent(ctx context.Context, agentID int64, limit int) ([]*chat_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgent", ctx, agentID, limit)
	ret0, _ := ret[0].([]*chat_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgent indicates an expected call of ListByAgent.
func (mr *MockSessionRepoMockRecorder) ListByAgent(ctx, agentID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgent", reflect.TypeOf((*MockSessionRepo)(nil).ListByAgent), ctx, agentID, limit)
}

// ListByAgentPaged mocks base method.
func (m *MockSessionRepo) ListByAgentPaged(ctx context.Context, agentID int64, offset, limit int) ([]*chat_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgentPaged", ctx, agentID, offset, limit)
	ret0, _ := ret[0].([]*chat_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgentPaged indicates an expected call of ListByAgentPaged.
func (mr *MockSessionRepoMockRecorder) ListByAgentPaged(ctx, agentID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgentPaged", reflect.TypeOf((*MockSessionRepo)(nil).ListByAgentPaged), ctx, agentID, offset, limit)
}

// ListByProject mocks base method.
func (m *MockSessionRepo) ListByProject(ctx context.Context, projectID int64) ([]*chat_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID)
	ret0, _ := ret[0].([]*chat_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockSessionRepoMockRecorder) ListByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockSessionRepo)(nil).ListByProject), ctx, projectID)
}

// ListIDsByAgents mocks base method.
func (m *MockSessionRepo) ListIDsByAgents(ctx context.Context, agentIDs []int64) (map[int64][]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIDsByAgents", ctx, agentIDs)
	ret0, _ := ret[0].(map[int64][]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIDsByAgents indicates an expected call of ListIDsByAgents.
func (mr *MockSessionRepoMockRecorder) ListIDsByAgents(ctx, agentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIDsByAgents", reflect.TypeOf((*MockSessionRepo)(nil).ListIDsByAgents), ctx, agentIDs)
}

// MarkRead mocks base method.
func (m *MockSessionRepo) MarkRead(ctx context.Context, sessionID, ts int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, sessionID, ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockSessionRepoMockRecorder) MarkRead(ctx, sessionID, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockSessionRepo)(nil).MarkRead), ctx, sessionID, ts)
}

// ResetActiveSessions mocks base method.
func (m *MockSessionRepo) ResetActiveSessions(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetActiveSessions", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetActiveSessions indicates an expected call of ResetActiveSessions.
func (mr *MockSessionRepoMockRecorder) ResetActiveSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetActiveSessions", reflect.TypeOf((*MockSessionRepo)(nil).ResetActiveSessions), ctx)
}

// SoftDelete mocks base method.
func (m *MockSessionRepo) SoftDelete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockSessionRepoMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockSessionRepo)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockSessionRepo) Update(ctx context.Context, s *chat_entity.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSessionRepoMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionRepo)(nil).Update), ctx, s)
}

// UpdatePermissionMode mocks base method.
func (m *MockSessionRepo) UpdatePermissionMode(ctx context.Context, sessionID int64, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermissionMode", ctx, sessionID, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePermissionMode indicates an expected call of UpdatePermissionMode.
func (mr *MockSessionRepoMockRecorder) UpdatePermissionMode(ctx, sessionID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermissionMode", reflect.TypeOf((*MockSessionRepo)(nil).UpdatePermissionMode), ctx, sessionID, mode)
}

// UpdatePermissionModeAtLaunch mocks base method.
func (m *MockSessionRepo) UpdatePermissionModeAtLaunch(ctx context.Context, sessionID int64, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermissionModeAtLaunch", ctx, sessionID, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePermissionModeAtLaunch indicates an expected call of UpdatePermissionModeAtLaunch.
func (mr *MockSessionRepoMockRecorder) UpdatePermissionModeAtLaunch(ctx, sessionID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermissionModeAtLaunch", reflect.TypeOf((*MockSessionRepo)(nil).UpdatePermissionModeAtLaunch), ctx, sessionID, mode)
}
