// Code generated by MockGen. DO NOT EDIT.
// Source: terminal.go
//
// Generated by this command:
//
//	mockgen -source=terminal.go -destination=mock_handlers/mock_terminal.go -package=mock_handlers
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	handlers "agentre/internal/daemon/handlers"
	pty "agentre/internal/pkg/pty"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPTYBackend is a mock of PTYBackend interface.
type MockPTYBackend struct {
	ctrl     *gomock.Controller
	recorder *MockPTYBackendMockRecorder
	isgomock struct{}
}

// MockPTYBackendMockRecorder is the mock recorder for MockPTYBackend.
type MockPTYBackendMockRecorder struct {
	mock *MockPTYBackend
}

// NewMockPTYBackend creates a new mock instance.
func NewMockPTYBackend(ctrl *gomock.Controller) *MockPTYBackend {
	mock := &MockPTYBackend{ctrl: ctrl}
	mock.recorder = &MockPTYBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPTYBackend) EXPECT() *MockPTYBackendMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockPTYBackend) Open(ctx context.Context, spec pty.Spec) (handlers.PTYHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, spec)
	ret0, _ := ret[0].(handlers.PTYHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockPTYBackendMockRecorder) Open(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockPTYBackend)(nil).Open), ctx, spec)
}

// MockPTYHandle is a mock of PTYHandle interface.
type MockPTYHandle struct {
	ctrl     *gomock.Controller
	recorder *MockPTYHandleMockRecorder
	isgomock struct{}
}

// MockPTYHandleMockRecorder is the mock recorder for MockPTYHandle.
type MockPTYHandleMockRecorder struct {
	mock *MockPTYHandle
}

// NewMockPTYHandle creates a new mock instance.
func NewMockPTYHandle(ctrl *gomock.Controller) *MockPTYHandle {
	mock := &MockPTYHandle{ctrl: ctrl}
	mock.recorder = &MockPTYHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPTYHandle) EXPECT() *MockPTYHandleMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPTYHandle) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPTYHandleMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPTYHandle)(nil).Close))
}

// Data mocks base method.
func (m *MockPTYHandle) Data() <-chan []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].(<-chan []byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockPTYHandleMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockPTYHandle)(nil).Data))
}

// Exit mocks base method.
func (m *MockPTYHandle) Exit() <-chan pty.ExitInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exit")
	ret0, _ := ret[0].(<-chan pty.ExitInfo)
	return ret0
}

// Exit indicates an expected call of Exit.
func (mr *MockPTYHandleMockRecorder) Exit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exit", reflect.TypeOf((*MockPTYHandle)(nil).Exit))
}

// Resize mocks base method.
func (m *MockPTYHandle) Resize(cols, rows uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", cols, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resize indicates an expected call of Resize.
func (mr *MockPTYHandleMockRecorder) Resize(cols, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockPTYHandle)(nil).Resize), cols, rows)
}

// Write mocks base method.
func (m *MockPTYHandle) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockPTYHandleMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockPTYHandle)(nil).Write), p)
}

// MockEmitter is a mock of Emitter interface.
type MockEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockEmitterMockRecorder
	isgomock struct{}
}

// MockEmitterMockRecorder is the mock recorder for MockEmitter.
type MockEmitterMockRecorder struct {
	mock *MockEmitter
}

// NewMockEmitter creates a new mock instance.
func NewMockEmitter(ctrl *gomock.Controller) *MockEmitter {
	mock := &MockEmitter{ctrl: ctrl}
	mock.recorder = &MockEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmitter) EXPECT() *MockEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockEmitter) Emit(ctx context.Context, name string, payload any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", ctx, name, payload)
}

// Emit indicates an expected call of Emit.
func (mr *MockEmitterMockRecorder) Emit(ctx, name, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockEmitter)(nil).Emit), ctx, name, payload)
}
