// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_handlers/mock_ports.go -package mock_handlers
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	handlers "github.com/agentre-ai/agentre/internal/daemon/handlers"
	state "github.com/agentre-ai/agentre/internal/daemon/state"
	agent_backend_entity "github.com/agentre-ai/agentre/internal/model/entity/agent_backend_entity"
	llm_provider_entity "github.com/agentre-ai/agentre/internal/model/entity/llm_provider_entity"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStatePort is a mock of StatePort interface.
type MockStatePort struct {
	ctrl     *gomock.Controller
	recorder *MockStatePortMockRecorder
	isgomock struct{}
}

// MockStatePortMockRecorder is the mock recorder for MockStatePort.
type MockStatePortMockRecorder struct {
	mock *MockStatePort
}

// NewMockStatePort creates a new mock instance.
func NewMockStatePort(ctrl *gomock.Controller) *MockStatePort {
	mock := &MockStatePort{ctrl: ctrl}
	mock.recorder = &MockStatePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatePort) EXPECT() *MockStatePortMockRecorder {
	return m.recorder
}

// Mutate mocks base method.
func (m *MockStatePort) Mutate(arg0 func(*state.State)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Mutate", arg0)
}

// Mutate indicates an expected call of Mutate.
func (mr *MockStatePortMockRecorder) Mutate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mutate", reflect.TypeOf((*MockStatePort)(nil).Mutate), arg0)
}

// Save mocks base method.
func (m *MockStatePort) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStatePortMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStatePort)(nil).Save))
}

// Snapshot mocks base method.
func (m *MockStatePort) Snapshot() state.State {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot")
	ret0, _ := ret[0].(state.State)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockStatePortMockRecorder) Snapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockStatePort)(nil).Snapshot))
}

// MockSessionRegistryPort is a mock of SessionRegistryPort interface.
type MockSessionRegistryPort struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRegistryPortMockRecorder
	isgomock struct{}
}

// MockSessionRegistryPortMockRecorder is the mock recorder for MockSessionRegistryPort.
type MockSessionRegistryPortMockRecorder struct {
	mock *MockSessionRegistryPort
}

// NewMockSessionRegistryPort creates a new mock instance.
func NewMockSessionRegistryPort(ctrl *gomock.Controller) *MockSessionRegistryPort {
	mock := &MockSessionRegistryPort{ctrl: ctrl}
	mock.recorder = &MockSessionRegistryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRegistryPort) EXPECT() *MockSessionRegistryPortMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSessionRegistryPort) List() []handlers.SessionHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]handlers.SessionHandle)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockSessionRegistryPortMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionRegistryPort)(nil).List))
}

// Lookup mocks base method.
func (m *MockSessionRegistryPort) Lookup(sessionID string) (handlers.SessionHandle, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", sessionID)
	ret0, _ := ret[0].(handlers.SessionHandle)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockSessionRegistryPortMockRecorder) Lookup(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockSessionRegistryPort)(nil).Lookup), sessionID)
}

// Register mocks base method.
func (m *MockSessionRegistryPort) Register(sessionID string, h handlers.SessionHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", sessionID, h)
}

// Register indicates an expected call of Register.
func (mr *MockSessionRegistryPortMockRecorder) Register(sessionID, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockSessionRegistryPort)(nil).Register), sessionID, h)
}

// Remove mocks base method.
func (m *MockSessionRegistryPort) Remove(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", sessionID)
}

// Remove indicates an expected call of Remove.
func (mr *MockSessionRegistryPortMockRecorder) Remove(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockSessionRegistryPort)(nil).Remove), sessionID)
}

// MockNotifierPort is a mock of NotifierPort interface.
type MockNotifierPort struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierPortMockRecorder
	isgomock struct{}
}

// MockNotifierPortMockRecorder is the mock recorder for MockNotifierPort.
type MockNotifierPortMockRecorder struct {
	mock *MockNotifierPort
}

// NewMockNotifierPort creates a new mock instance.
func NewMockNotifierPort(ctrl *gomock.Controller) *MockNotifierPort {
	mock := &MockNotifierPort{ctrl: ctrl}
	mock.recorder = &MockNotifierPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifierPort) EXPECT() *MockNotifierPortMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotifierPort) Notify(method string, params any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", method, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNotifierPortMockRecorder) Notify(method, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifierPort)(nil).Notify), method, params)
}

// Request mocks base method.
func (m *MockNotifierPort) Request(ctx context.Context, method string, params, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, method, params, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockNotifierPortMockRecorder) Request(ctx, method, params, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockNotifierPort)(nil).Request), ctx, method, params, result)
}

// MockGatewayPort is a mock of GatewayPort interface.
type MockGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayPortMockRecorder
	isgomock struct{}
}

// MockGatewayPortMockRecorder is the mock recorder for MockGatewayPort.
type MockGatewayPortMockRecorder struct {
	mock *MockGatewayPort
}

// NewMockGatewayPort creates a new mock instance.
func NewMockGatewayPort(ctrl *gomock.Controller) *MockGatewayPort {
	mock := &MockGatewayPort{ctrl: ctrl}
	mock.recorder = &MockGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayPort) EXPECT() *MockGatewayPortMockRecorder {
	return m.recorder
}

// IssueToken mocks base method.
func (m *MockGatewayPort) IssueToken(ctx context.Context, b *agent_backend_entity.AgentBackend, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueToken", ctx, b, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueToken indicates an expected call of IssueToken.
func (mr *MockGatewayPortMockRecorder) IssueToken(ctx, b, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueToken", reflect.TypeOf((*MockGatewayPort)(nil).IssueToken), ctx, b, ttl)
}

// RevokeToken mocks base method.
func (m *MockGatewayPort) RevokeToken(token string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevokeToken", token)
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockGatewayPortMockRecorder) RevokeToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockGatewayPort)(nil).RevokeToken), token)
}

// URL mocks base method.
func (m *MockGatewayPort) URL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL")
	ret0, _ := ret[0].(string)
	return ret0
}

// URL indicates an expected call of URL.
func (mr *MockGatewayPortMockRecorder) URL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockGatewayPort)(nil).URL))
}

// MockLLMProviderLookupPort is a mock of LLMProviderLookupPort interface.
type MockLLMProviderLookupPort struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderLookupPortMockRecorder
	isgomock struct{}
}

// MockLLMProviderLookupPortMockRecorder is the mock recorder for MockLLMProviderLookupPort.
type MockLLMProviderLookupPortMockRecorder struct {
	mock *MockLLMProviderLookupPort
}

// NewMockLLMProviderLookupPort creates a new mock instance.
func NewMockLLMProviderLookupPort(ctrl *gomock.Controller) *MockLLMProviderLookupPort {
	mock := &MockLLMProviderLookupPort{ctrl: ctrl}
	mock.recorder = &MockLLMProviderLookupPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProviderLookupPort) EXPECT() *MockLLMProviderLookupPortMockRecorder {
	return m.recorder
}

// FindByKey mocks base method.
func (m *MockLLMProviderLookupPort) FindByKey(ctx context.Context, key string) (*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKey", ctx, key)
	ret0, _ := ret[0].(*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKey indicates an expected call of FindByKey.
func (mr *MockLLMProviderLookupPortMockRecorder) FindByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKey", reflect.TypeOf((*MockLLMProviderLookupPort)(nil).FindByKey), ctx, key)
}
