// Code generated by MockGen. DO NOT EDIT.
// Source: notification.go
//
// Generated by this command:
//
//	mockgen -source notification.go -destination mock_notification_svc/mock_notification.go
//

// Package mock_notification_svc is a generated GoMock package.
package mock_notification_svc

import (
	notification_svc "agentre/internal/service/notification_svc"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotifier) Notify(ctx context.Context, title, body string, sessionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, title, body, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNotifierMockRecorder) Notify(ctx, title, body, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifier)(nil).Notify), ctx, title, body, sessionID)
}

// MockNotificationSvc is a mock of NotificationSvc interface.
type MockNotificationSvc struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSvcMockRecorder
	isgomock struct{}
}

// MockNotificationSvcMockRecorder is the mock recorder for MockNotificationSvc.
type MockNotificationSvcMockRecorder struct {
	mock *MockNotificationSvc
}

// NewMockNotificationSvc creates a new mock instance.
func NewMockNotificationSvc(ctrl *gomock.Controller) *MockNotificationSvc {
	mock := &MockNotificationSvc{ctrl: ctrl}
	mock.recorder = &MockNotificationSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationSvc) EXPECT() *MockNotificationSvcMockRecorder {
	return m.recorder
}

// Show mocks base method.
func (m *MockNotificationSvc) Show(ctx context.Context, req *notification_svc.ShowRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Show indicates an expected call of Show.
func (mr *MockNotificationSvcMockRecorder) Show(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockNotificationSvc)(nil).Show), ctx, req)
}
