// Code generated by MockGen. DO NOT EDIT.
// Source: agent.go
//
// Generated by this command:
//
//	mockgen -source agent.go -destination mock_agent_repo/mock_agent.go
//

// Package mock_agent_repo is a generated GoMock package.
package mock_agent_repo

import (
	agent_entity "agentre/internal/model/entity/agent_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAgentRepo is a mock of AgentRepo interface.
type MockAgentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRepoMockRecorder
	isgomock struct{}
}

// MockAgentRepoMockRecorder is the mock recorder for MockAgentRepo.
type MockAgentRepoMockRecorder struct {
	mock *MockAgentRepo
}

// NewMockAgentRepo creates a new mock instance.
func NewMockAgentRepo(ctrl *gomock.Controller) *MockAgentRepo {
	mock := &MockAgentRepo{ctrl: ctrl}
	mock.recorder = &MockAgentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRepo) EXPECT() *MockAgentRepoMockRecorder {
	return m.recorder
}

// ClearLeadOfDepartment mocks base method.
func (m *MockAgentRepo) ClearLeadOfDepartment(ctx context.Context, agentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearLeadOfDepartment", ctx, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearLeadOfDepartment indicates an expected call of ClearLeadOfDepartment.
func (mr *MockAgentRepoMockRecorder) ClearLeadOfDepartment(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearLeadOfDepartment", reflect.TypeOf((*MockAgentRepo)(nil).ClearLeadOfDepartment), ctx, agentID)
}

// CountByBackends mocks base method.
func (m *MockAgentRepo) CountByBackends(ctx context.Context, backendIDs []int64) (map[int64]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByBackends", ctx, backendIDs)
	ret0, _ := ret[0].(map[int64]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByBackends indicates an expected call of CountByBackends.
func (mr *MockAgentRepoMockRecorder) CountByBackends(ctx, backendIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByBackends", reflect.TypeOf((*MockAgentRepo)(nil).CountByBackends), ctx, backendIDs)
}

// Create mocks base method.
func (m *MockAgentRepo) Create(ctx context.Context, a *agent_entity.Agent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAgentRepoMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentRepo)(nil).Create), ctx, a)
}

// Delete mocks base method.
func (m *MockAgentRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentRepo)(nil).Delete), ctx, id)
}

// DeleteByDepartment mocks base method.
func (m *MockAgentRepo) DeleteByDepartment(ctx context.Context, departmentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByDepartment", ctx, departmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByDepartment indicates an expected call of DeleteByDepartment.
func (mr *MockAgentRepoMockRecorder) DeleteByDepartment(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByDepartment", reflect.TypeOf((*MockAgentRepo)(nil).DeleteByDepartment), ctx, departmentID)
}

// Find mocks base method.
func (m *MockAgentRepo) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockAgentRepo) FindByName(ctx context.Context, name string) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockAgentRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockAgentRepo)(nil).FindByName), ctx, name)
}

// FindSystem mocks base method.
func (m *MockAgentRepo) FindSystem(ctx context.Context) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSystem", ctx)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSystem indicates an expected call of FindSystem.
func (mr *MockAgentRepoMockRecorder) FindSystem(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSystem", reflect.TypeOf((*MockAgentRepo)(nil).FindSystem), ctx)
}

// List mocks base method.
func (m *MockAgentRepo) List(ctx context.Context) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentRepo)(nil).List), ctx)
}

// ListByBackend mocks base method.
func (m *MockAgentRepo) ListByBackend(ctx context.Context, backendID int64) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBackend", ctx, backendID)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByBackend indicates an expected call of ListByBackend.
func (mr *MockAgentRepoMockRecorder) ListByBackend(ctx, backendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBackend", reflect.TypeOf((*MockAgentRepo)(nil).ListByBackend), ctx, backendID)
}

// ListByDepartment mocks base method.
func (m *MockAgentRepo) ListByDepartment(ctx context.Context, departmentID int64) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDepartment", ctx, departmentID)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDepartment indicates an expected call of ListByDepartment.
func (mr *MockAgentRepoMockRecorder) ListByDepartment(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDepartment", reflect.TypeOf((*MockAgentRepo)(nil).ListByDepartment), ctx, departmentID)
}

// ListByParent mocks base method.
func (m *MockAgentRepo) ListByParent(ctx context.Context, parentAgentID int64) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByParent", ctx, parentAgentID)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByParent indicates an expected call of ListByParent.
func (mr *MockAgentRepoMockRecorder) ListByParent(ctx, parentAgentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByParent", reflect.TypeOf((*MockAgentRepo)(nil).ListByParent), ctx, parentAgentID)
}

// NextSortOrder mocks base method.
func (m *MockAgentRepo) NextSortOrder(ctx context.Context, departmentID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSortOrder", ctx, departmentID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSortOrder indicates an expected call of NextSortOrder.
func (mr *MockAgentRepoMockRecorder) NextSortOrder(ctx, departmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSortOrder", reflect.TypeOf((*MockAgentRepo)(nil).NextSortOrder), ctx, departmentID)
}

// NextSortOrderByParent mocks base method.
func (m *MockAgentRepo) NextSortOrderByParent(ctx context.Context, parentAgentID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSortOrderByParent", ctx, parentAgentID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSortOrderByParent indicates an expected call of NextSortOrderByParent.
func (mr *MockAgentRepoMockRecorder) NextSortOrderByParent(ctx, parentAgentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSortOrderByParent", reflect.TypeOf((*MockAgentRepo)(nil).NextSortOrderByParent), ctx, parentAgentID)
}

// ReparentChildren mocks base method.
func (m *MockAgentRepo) ReparentChildren(ctx context.Context, fromParentAgentID, toDepartmentID, toParentAgentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReparentChildren", ctx, fromParentAgentID, toDepartmentID, toParentAgentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReparentChildren indicates an expected call of ReparentChildren.
func (mr *MockAgentRepoMockRecorder) ReparentChildren(ctx, fromParentAgentID, toDepartmentID, toParentAgentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReparentChildren", reflect.TypeOf((*MockAgentRepo)(nil).ReparentChildren), ctx, fromParentAgentID, toDepartmentID, toParentAgentID)
}

// Update mocks base method.
func (m *MockAgentRepo) Update(ctx context.Context, a *agent_entity.Agent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAgentRepoMockRecorder) Update(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentRepo)(nil).Update), ctx, a)
}

// UpdateAvatar mocks base method.
func (m *MockAgentRepo) UpdateAvatar(ctx context.Context, id int64, avatarDataURL string, updatetime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, id, avatarDataURL, updatetime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockAgentRepoMockRecorder) UpdateAvatar(ctx, id, avatarDataURL, updatetime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockAgentRepo)(nil).UpdateAvatar), ctx, id, avatarDataURL, updatetime)
}

// UpdateDepartment mocks base method.
func (m *MockAgentRepo) UpdateDepartment(ctx context.Context, id, departmentID int64, sortOrder int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartment", ctx, id, departmentID, sortOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDepartment indicates an expected call of UpdateDepartment.
func (mr *MockAgentRepoMockRecorder) UpdateDepartment(ctx, id, departmentID, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartment", reflect.TypeOf((*MockAgentRepo)(nil).UpdateDepartment), ctx, id, departmentID, sortOrder)
}

// UpdatePlacement mocks base method.
func (m *MockAgentRepo) UpdatePlacement(ctx context.Context, id, departmentID, parentAgentID int64, sortOrder int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlacement", ctx, id, departmentID, parentAgentID, sortOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlacement indicates an expected call of UpdatePlacement.
func (mr *MockAgentRepoMockRecorder) UpdatePlacement(ctx, id, departmentID, parentAgentID, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlacement", reflect.TypeOf((*MockAgentRepo)(nil).UpdatePlacement), ctx, id, departmentID, parentAgentID, sortOrder)
}
