// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination mock_remote_fs_svc/mock_svc.go
//

// Package mock_remote_fs_svc is a generated GoMock package.
package mock_remote_fs_svc

import (
	context "context"
	remote_fs_svc "github.com/agentre-ai/agentre/internal/service/remote_fs_svc"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoteFsSvc is a mock of RemoteFsSvc interface.
type MockRemoteFsSvc struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteFsSvcMockRecorder
	isgomock struct{}
}

// MockRemoteFsSvcMockRecorder is the mock recorder for MockRemoteFsSvc.
type MockRemoteFsSvcMockRecorder struct {
	mock *MockRemoteFsSvc
}

// NewMockRemoteFsSvc creates a new mock instance.
func NewMockRemoteFsSvc(ctrl *gomock.Controller) *MockRemoteFsSvc {
	mock := &MockRemoteFsSvc{ctrl: ctrl}
	mock.recorder = &MockRemoteFsSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteFsSvc) EXPECT() *MockRemoteFsSvcMockRecorder {
	return m.recorder
}

// ListDir mocks base method.
func (m *MockRemoteFsSvc) ListDir(ctx context.Context, deviceID, path string) (*remote_fs_svc.ListDirView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDir", ctx, deviceID, path)
	ret0, _ := ret[0].(*remote_fs_svc.ListDirView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDir indicates an expected call of ListDir.
func (mr *MockRemoteFsSvcMockRecorder) ListDir(ctx, deviceID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDir", reflect.TypeOf((*MockRemoteFsSvc)(nil).ListDir), ctx, deviceID, path)
}

// Mkdir mocks base method.
func (m *MockRemoteFsSvc) Mkdir(ctx context.Context, deviceID, parent, name string) (*remote_fs_svc.MkdirView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mkdir", ctx, deviceID, parent, name)
	ret0, _ := ret[0].(*remote_fs_svc.MkdirView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mkdir indicates an expected call of Mkdir.
func (mr *MockRemoteFsSvcMockRecorder) Mkdir(ctx, deviceID, parent, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*MockRemoteFsSvc)(nil).Mkdir), ctx, deviceID, parent, name)
}
