// Code generated by MockGen. DO NOT EDIT.
// Source: server_state.go
//
// Generated by this command:
//
//	mockgen -source server_state.go -destination mock_server_state_repo/mock_server_state.go
//

// Package mock_server_state_repo is a generated GoMock package.
package mock_server_state_repo

import (
	server_state_entity "agentre/internal/model/entity/server_state_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServerStateRepo is a mock of ServerStateRepo interface.
type MockServerStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockServerStateRepoMockRecorder
	isgomock struct{}
}

// MockServerStateRepoMockRecorder is the mock recorder for MockServerStateRepo.
type MockServerStateRepoMockRecorder struct {
	mock *MockServerStateRepo
}

// NewMockServerStateRepo creates a new mock instance.
func NewMockServerStateRepo(ctrl *gomock.Controller) *MockServerStateRepo {
	mock := &MockServerStateRepo{ctrl: ctrl}
	mock.recorder = &MockServerStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerStateRepo) EXPECT() *MockServerStateRepoMockRecorder {
	return m.recorder
}

// ClearLoginFields mocks base method.
func (m *MockServerStateRepo) ClearLoginFields(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearLoginFields", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearLoginFields indicates an expected call of ClearLoginFields.
func (mr *MockServerStateRepoMockRecorder) ClearLoginFields(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearLoginFields", reflect.TypeOf((*MockServerStateRepo)(nil).ClearLoginFields), ctx)
}

// Get mocks base method.
func (m *MockServerStateRepo) Get(ctx context.Context) (*server_state_entity.ServerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*server_state_entity.ServerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServerStateRepoMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServerStateRepo)(nil).Get), ctx)
}

// Save mocks base method.
func (m *MockServerStateRepo) Save(ctx context.Context, e *server_state_entity.ServerState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServerStateRepoMockRecorder) Save(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockServerStateRepo)(nil).Save), ctx, e)
}
