// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination mock_data_svc/mock_data_svc.go
//

// Package mock_data_svc is a generated GoMock package.
package mock_data_svc

import (
	context "context"
	data_svc "github.com/agentre-ai/agentre/internal/service/data_svc"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDataSvc is a mock of DataSvc interface.
type MockDataSvc struct {
	ctrl     *gomock.Controller
	recorder *MockDataSvcMockRecorder
	isgomock struct{}
}

// MockDataSvcMockRecorder is the mock recorder for MockDataSvc.
type MockDataSvcMockRecorder struct {
	mock *MockDataSvc
}

// NewMockDataSvc creates a new mock instance.
func NewMockDataSvc(ctrl *gomock.Controller) *MockDataSvc {
	mock := &MockDataSvc{ctrl: ctrl}
	mock.recorder = &MockDataSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSvc) EXPECT() *MockDataSvcMockRecorder {
	return m.recorder
}

// ApplyImport mocks base method.
func (m *MockDataSvc) ApplyImport(ctx context.Context, req *data_svc.ApplyImportRequest) (*data_svc.ApplyImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyImport", ctx, req)
	ret0, _ := ret[0].(*data_svc.ApplyImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyImport indicates an expected call of ApplyImport.
func (mr *MockDataSvcMockRecorder) ApplyImport(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyImport", reflect.TypeOf((*MockDataSvc)(nil).ApplyImport), ctx, req)
}

// Export mocks base method.
func (m *MockDataSvc) Export(ctx context.Context, req *data_svc.ExportRequest) (*data_svc.ExportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", ctx, req)
	ret0, _ := ret[0].(*data_svc.ExportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockDataSvcMockRecorder) Export(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockDataSvc)(nil).Export), ctx, req)
}

// PreviewImport mocks base method.
func (m *MockDataSvc) PreviewImport(ctx context.Context, raw []byte) (*data_svc.ImportPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewImport", ctx, raw)
	ret0, _ := ret[0].(*data_svc.ImportPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewImport indicates an expected call of PreviewImport.
func (mr *MockDataSvcMockRecorder) PreviewImport(ctx, raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewImport", reflect.TypeOf((*MockDataSvc)(nil).PreviewImport), ctx, raw)
}
