// Code generated by MockGen. DO NOT EDIT.
// Source: backend.go
//
// Generated by this command:
//
//	mockgen -source=backend.go -destination=mocks/mock_backend.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	pty "agentre/internal/pkg/pty"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPTYBackend is a mock of PTYBackend interface.
type MockPTYBackend struct {
	ctrl     *gomock.Controller
	recorder *MockPTYBackendMockRecorder
	isgomock struct{}
}

// MockPTYBackendMockRecorder is the mock recorder for MockPTYBackend.
type MockPTYBackendMockRecorder struct {
	mock *MockPTYBackend
}

// NewMockPTYBackend creates a new mock instance.
func NewMockPTYBackend(ctrl *gomock.Controller) *MockPTYBackend {
	mock := &MockPTYBackend{ctrl: ctrl}
	mock.recorder = &MockPTYBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPTYBackend) EXPECT() *MockPTYBackendMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockPTYBackend) Open(ctx context.Context, spec pty.Spec) (pty.Handle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, spec)
	ret0, _ := ret[0].(pty.Handle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockPTYBackendMockRecorder) Open(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockPTYBackend)(nil).Open), ctx, spec)
}
