// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mock_orgtool_svc/mock_deps.go
//

// Package mock_orgtool_svc is a generated GoMock package.
package mock_orgtool_svc

import (
	context "context"
	reflect "reflect"

	agent_entity "github.com/agentre-ai/agentre/internal/model/entity/agent_entity"
	agent_svc "github.com/agentre-ai/agentre/internal/service/agent_svc"
	blocks "github.com/agentre-ai/agentre/internal/service/chat_svc/blocks"
	department_svc "github.com/agentre-ai/agentre/internal/service/department_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockOrgQuery is a mock of OrgQuery interface.
type MockOrgQuery struct {
	ctrl     *gomock.Controller
	recorder *MockOrgQueryMockRecorder
	isgomock struct{}
}

// MockOrgQueryMockRecorder is the mock recorder for MockOrgQuery.
type MockOrgQueryMockRecorder struct {
	mock *MockOrgQuery
}

// NewMockOrgQuery creates a new mock instance.
func NewMockOrgQuery(ctrl *gomock.Controller) *MockOrgQuery {
	mock := &MockOrgQuery{ctrl: ctrl}
	mock.recorder = &MockOrgQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgQuery) EXPECT() *MockOrgQueryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockOrgQuery) Load(ctx context.Context, req *department_svc.LoadOrgRequest) (*department_svc.LoadOrgResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, req)
	ret0, _ := ret[0].(*department_svc.LoadOrgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockOrgQueryMockRecorder) Load(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockOrgQuery)(nil).Load), ctx, req)
}

// MockDeptCommand is a mock of DeptCommand interface.
type MockDeptCommand struct {
	ctrl     *gomock.Controller
	recorder *MockDeptCommandMockRecorder
	isgomock struct{}
}

// MockDeptCommandMockRecorder is the mock recorder for MockDeptCommand.
type MockDeptCommandMockRecorder struct {
	mock *MockDeptCommand
}

// NewMockDeptCommand creates a new mock instance.
func NewMockDeptCommand(ctrl *gomock.Controller) *MockDeptCommand {
	mock := &MockDeptCommand{ctrl: ctrl}
	mock.recorder = &MockDeptCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeptCommand) EXPECT() *MockDeptCommandMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeptCommand) Create(ctx context.Context, req *department_svc.CreateDepartmentRequest) (*department_svc.CreateDepartmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*department_svc.CreateDepartmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeptCommandMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeptCommand)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockDeptCommand) Delete(ctx context.Context, req *department_svc.DeleteDepartmentRequest) (*department_svc.DeleteDepartmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*department_svc.DeleteDepartmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDeptCommandMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeptCommand)(nil).Delete), ctx, req)
}

// Move mocks base method.
func (m *MockDeptCommand) Move(ctx context.Context, req *department_svc.MoveDepartmentRequest) (*department_svc.MoveDepartmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, req)
	ret0, _ := ret[0].(*department_svc.MoveDepartmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Move indicates an expected call of Move.
func (mr *MockDeptCommandMockRecorder) Move(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockDeptCommand)(nil).Move), ctx, req)
}

// Update mocks base method.
func (m *MockDeptCommand) Update(ctx context.Context, req *department_svc.UpdateDepartmentRequest) (*department_svc.UpdateDepartmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*department_svc.UpdateDepartmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDeptCommandMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeptCommand)(nil).Update), ctx, req)
}

// MockAgentCommand is a mock of AgentCommand interface.
type MockAgentCommand struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCommandMockRecorder
	isgomock struct{}
}

// MockAgentCommandMockRecorder is the mock recorder for MockAgentCommand.
type MockAgentCommandMockRecorder struct {
	mock *MockAgentCommand
}

// NewMockAgentCommand creates a new mock instance.
func NewMockAgentCommand(ctrl *gomock.Controller) *MockAgentCommand {
	mock := &MockAgentCommand{ctrl: ctrl}
	mock.recorder = &MockAgentCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCommand) EXPECT() *MockAgentCommandMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAgentCommand) Create(ctx context.Context, req *agent_svc.CreateAgentRequest) (*agent_svc.CreateAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*agent_svc.CreateAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAgentCommandMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentCommand)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockAgentCommand) Delete(ctx context.Context, req *agent_svc.DeleteAgentRequest) (*agent_svc.DeleteAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*agent_svc.DeleteAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentCommandMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentCommand)(nil).Delete), ctx, req)
}

// Move mocks base method.
func (m *MockAgentCommand) Move(ctx context.Context, req *agent_svc.MoveAgentRequest) (*agent_svc.MoveAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, req)
	ret0, _ := ret[0].(*agent_svc.MoveAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Move indicates an expected call of Move.
func (mr *MockAgentCommandMockRecorder) Move(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockAgentCommand)(nil).Move), ctx, req)
}

// Update mocks base method.
func (m *MockAgentCommand) Update(ctx context.Context, req *agent_svc.UpdateAgentRequest) (*agent_svc.UpdateAgentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*agent_svc.UpdateAgentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAgentCommandMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentCommand)(nil).Update), ctx, req)
}

// MockAgentLookup is a mock of AgentLookup interface.
type MockAgentLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAgentLookupMockRecorder
	isgomock struct{}
}

// MockAgentLookupMockRecorder is the mock recorder for MockAgentLookup.
type MockAgentLookupMockRecorder struct {
	mock *MockAgentLookup
}

// NewMockAgentLookup creates a new mock instance.
func NewMockAgentLookup(ctrl *gomock.Controller) *MockAgentLookup {
	mock := &MockAgentLookup{ctrl: ctrl}
	mock.recorder = &MockAgentLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentLookup) EXPECT() *MockAgentLookupMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentLookup) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentLookupMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentLookup)(nil).Find), ctx, id)
}

// MockApprovalGateway is a mock of ApprovalGateway interface.
type MockApprovalGateway struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalGatewayMockRecorder
	isgomock struct{}
}

// MockApprovalGatewayMockRecorder is the mock recorder for MockApprovalGateway.
type MockApprovalGatewayMockRecorder struct {
	mock *MockApprovalGateway
}

// NewMockApprovalGateway creates a new mock instance.
func NewMockApprovalGateway(ctrl *gomock.Controller) *MockApprovalGateway {
	mock := &MockApprovalGateway{ctrl: ctrl}
	mock.recorder = &MockApprovalGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalGateway) EXPECT() *MockApprovalGatewayMockRecorder {
	return m.recorder
}

// BeginToolApproval mocks base method.
func (m *MockApprovalGateway) BeginToolApproval(ctx context.Context, sessionID int64, blk *blocks.ToolApprovalBlock) (<-chan bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginToolApproval", ctx, sessionID, blk)
	ret0, _ := ret[0].(<-chan bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginToolApproval indicates an expected call of BeginToolApproval.
func (mr *MockApprovalGatewayMockRecorder) BeginToolApproval(ctx, sessionID, blk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginToolApproval", reflect.TypeOf((*MockApprovalGateway)(nil).BeginToolApproval), ctx, sessionID, blk)
}

// FinishToolApproval mocks base method.
func (m *MockApprovalGateway) FinishToolApproval(ctx context.Context, sessionID int64, requestID, status, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishToolApproval", ctx, sessionID, requestID, status, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishToolApproval indicates an expected call of FinishToolApproval.
func (mr *MockApprovalGatewayMockRecorder) FinishToolApproval(ctx, sessionID, requestID, status, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishToolApproval", reflect.TypeOf((*MockApprovalGateway)(nil).FinishToolApproval), ctx, sessionID, requestID, status, result)
}
