package httpgateway

import "sync"

// SteerItem is one queued Steer message: a stable id (generated by chat_svc
// when Enqueue is called) + the user-supplied text. The id is what
// SteerCanceler.CancelSteer addresses for selective withdrawal.
type SteerItem struct {
	ID   string
	Text string
}

// SteerInbox is the in-process queue of pending Steer messages per claude
// session UUID. The claudecode runner Push()es when chat_svc.Enqueue is
// called; the agentre claudecode hook child process pulls via HTTP and the
// handler calls Drain to consume + clear.
//
// Drain is destructive (read once, then clear). If a hook process pulls and
// then crashes the messages are lost — by design for the MVP.
type SteerInbox struct {
	mu sync.Mutex
	q  map[string][]SteerItem
	s  map[string]map[*steerDrainSub]struct{}
}

type steerDrainSub struct {
	ch     chan []SteerItem
	closed bool
}

// NewSteerInbox returns an empty inbox.
func NewSteerInbox() *SteerInbox {
	return &SteerInbox{
		q: make(map[string][]SteerItem),
		s: make(map[string]map[*steerDrainSub]struct{}),
	}
}

// Push appends an item to the queue for sid. Concurrent-safe.
// Empty sid or empty id is a no-op (empty id would create uncancellable
// entries colliding with each other on Remove).
func (s *SteerInbox) Push(sid, id, text string) {
	if sid == "" || id == "" {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.q[sid] = append(s.q[sid], SteerItem{ID: id, Text: text})
}

// Drain returns the queue for sid (in FIFO order) and clears it.
// Returns nil if there are no pending messages.
func (s *SteerInbox) Drain(sid string) []SteerItem {
	s.mu.Lock()
	out := s.q[sid]
	delete(s.q, sid)
	if len(out) > 0 {
		for sub := range s.s[sid] {
			if sub.closed {
				continue
			}
			select {
			case sub.ch <- cloneSteerItems(out):
			default:
			}
		}
	}
	s.mu.Unlock()
	return out
}

// SubscribeDrain returns a channel that receives every non-empty Drain batch for
// sid. It is used by the runner that owns the active Claude session to turn a
// hook-side queue drain into a UI-visible "steer consumed" stream event.
func (s *SteerInbox) SubscribeDrain(sid string) (<-chan []SteerItem, func()) {
	ch := make(chan []SteerItem, 16)
	if sid == "" {
		close(ch)
		return ch, func() {}
	}
	sub := &steerDrainSub{ch: ch}
	s.mu.Lock()
	if s.s[sid] == nil {
		s.s[sid] = make(map[*steerDrainSub]struct{})
	}
	s.s[sid][sub] = struct{}{}
	s.mu.Unlock()

	var once sync.Once
	cancel := func() {
		once.Do(func() {
			s.mu.Lock()
			if subs := s.s[sid]; subs != nil {
				delete(subs, sub)
				if len(subs) == 0 {
					delete(s.s, sid)
				}
			}
			sub.closed = true
			s.mu.Unlock()
			close(ch)
		})
	}
	return ch, cancel
}

// Remove deletes the queued entry with matching id from sid's queue without
// affecting other entries. Returns true on hit, false if sid or id is unknown
// (the entry was already drained / never existed).
func (s *SteerInbox) Remove(sid, id string) bool {
	if sid == "" || id == "" {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	items, ok := s.q[sid]
	if !ok {
		return false
	}
	for i, it := range items {
		if it.ID == id {
			items = append(items[:i], items[i+1:]...)
			if len(items) == 0 {
				delete(s.q, sid)
			} else {
				s.q[sid] = items
			}
			return true
		}
	}
	return false
}

// Forget removes the queue for sid without returning it. Used when a turn
// completes / aborts and we no longer want stale messages to be visible.
func (s *SteerInbox) Forget(sid string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.q, sid)
}

func cloneSteerItems(in []SteerItem) []SteerItem {
	if len(in) == 0 {
		return nil
	}
	out := make([]SteerItem, len(in))
	copy(out, in)
	return out
}
