// Code generated by MockGen. DO NOT EDIT.
// Source: workflow.go
//
// Generated by this command:
//
//	mockgen -source workflow.go -destination mock_workflow_repo/mock_workflow.go
//

// Package mock_workflow_repo is a generated GoMock package.
package mock_workflow_repo

import (
	context "context"
	reflect "reflect"

	workflow_entity "github.com/agentre-ai/agentre/internal/model/entity/workflow_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowRepo is a mock of WorkflowRepo interface.
type MockWorkflowRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRepoMockRecorder
	isgomock struct{}
}

// MockWorkflowRepoMockRecorder is the mock recorder for MockWorkflowRepo.
type MockWorkflowRepoMockRecorder struct {
	mock *MockWorkflowRepo
}

// NewMockWorkflowRepo creates a new mock instance.
func NewMockWorkflowRepo(ctrl *gomock.Controller) *MockWorkflowRepo {
	mock := &MockWorkflowRepo{ctrl: ctrl}
	mock.recorder = &MockWorkflowRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRepo) EXPECT() *MockWorkflowRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkflowRepo) Create(ctx context.Context, w *workflow_entity.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkflowRepoMockRecorder) Create(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkflowRepo)(nil).Create), ctx, w)
}

// Delete mocks base method.
func (m *MockWorkflowRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkflowRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockWorkflowRepo) Find(ctx context.Context, id int64) (*workflow_entity.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*workflow_entity.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockWorkflowRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockWorkflowRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockWorkflowRepo) List(ctx context.Context) ([]*workflow_entity.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*workflow_entity.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWorkflowRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkflowRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockWorkflowRepo) Update(ctx context.Context, w *workflow_entity.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWorkflowRepoMockRecorder) Update(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowRepo)(nil).Update), ctx, w)
}
