// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go
//
// Generated by this command:
//
//	mockgen -source gateway.go -destination mock_group_svc/mock_gateway.go
//

// Package mock_group_svc is a generated GoMock package.
package mock_group_svc

import (
	context "context"
	capability "github.com/agentre-ai/agentre/internal/pkg/agentruntime/capability"
	chat_svc "github.com/agentre-ai/agentre/internal/service/chat_svc"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatGateway is a mock of ChatGateway interface.
type MockChatGateway struct {
	ctrl     *gomock.Controller
	recorder *MockChatGatewayMockRecorder
	isgomock struct{}
}

// MockChatGatewayMockRecorder is the mock recorder for MockChatGateway.
type MockChatGatewayMockRecorder struct {
	mock *MockChatGateway
}

// NewMockChatGateway creates a new mock instance.
func NewMockChatGateway(ctrl *gomock.Controller) *MockChatGateway {
	mock := &MockChatGateway{ctrl: ctrl}
	mock.recorder = &MockChatGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatGateway) EXPECT() *MockChatGatewayMockRecorder {
	return m.recorder
}

// AgentBackendHasCapability mocks base method.
func (m *MockChatGateway) AgentBackendHasCapability(ctx context.Context, agentID int64, wantCap capability.Capability) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentBackendHasCapability", ctx, agentID, wantCap)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentBackendHasCapability indicates an expected call of AgentBackendHasCapability.
func (mr *MockChatGatewayMockRecorder) AgentBackendHasCapability(ctx, agentID, wantCap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentBackendHasCapability", reflect.TypeOf((*MockChatGateway)(nil).AgentBackendHasCapability), ctx, agentID, wantCap)
}

// DeleteSession mocks base method.
func (m *MockChatGateway) DeleteSession(ctx context.Context, sessionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockChatGatewayMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockChatGateway)(nil).DeleteSession), ctx, sessionID)
}

// EnsureSession mocks base method.
func (m *MockChatGateway) EnsureSession(ctx context.Context, req *chat_svc.EnsureSessionRequest) (*chat_svc.EnsureSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSession", ctx, req)
	ret0, _ := ret[0].(*chat_svc.EnsureSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureSession indicates an expected call of EnsureSession.
func (mr *MockChatGatewayMockRecorder) EnsureSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSession", reflect.TypeOf((*MockChatGateway)(nil).EnsureSession), ctx, req)
}

// ObserveTurn mocks base method.
func (m *MockChatGateway) ObserveTurn(sessionID int64) (<-chan chat_svc.TurnResult, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObserveTurn", sessionID)
	ret0, _ := ret[0].(<-chan chat_svc.TurnResult)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// ObserveTurn indicates an expected call of ObserveTurn.
func (mr *MockChatGatewayMockRecorder) ObserveTurn(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveTurn", reflect.TypeOf((*MockChatGateway)(nil).ObserveTurn), sessionID)
}

// Send mocks base method.
func (m *MockChatGateway) Send(ctx context.Context, req *chat_svc.SendRequest) (*chat_svc.SendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, req)
	ret0, _ := ret[0].(*chat_svc.SendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockChatGatewayMockRecorder) Send(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockChatGateway)(nil).Send), ctx, req)
}

// Stop mocks base method.
func (m *MockChatGateway) Stop(ctx context.Context, req *chat_svc.StopRequest) (*chat_svc.StopResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, req)
	ret0, _ := ret[0].(*chat_svc.StopResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stop indicates an expected call of Stop.
func (mr *MockChatGatewayMockRecorder) Stop(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockChatGateway)(nil).Stop), ctx, req)
}
