// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination mock_remote_device_svc/mock_svc.go
//

// Package mock_remote_device_svc is a generated GoMock package.
package mock_remote_device_svc

import (
	remote_device_svc "agentre/internal/service/remote_device_svc"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoteDeviceSvc is a mock of RemoteDeviceSvc interface.
type MockRemoteDeviceSvc struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteDeviceSvcMockRecorder
	isgomock struct{}
}

// MockRemoteDeviceSvcMockRecorder is the mock recorder for MockRemoteDeviceSvc.
type MockRemoteDeviceSvcMockRecorder struct {
	mock *MockRemoteDeviceSvc
}

// NewMockRemoteDeviceSvc creates a new mock instance.
func NewMockRemoteDeviceSvc(ctrl *gomock.Controller) *MockRemoteDeviceSvc {
	mock := &MockRemoteDeviceSvc{ctrl: ctrl}
	mock.recorder = &MockRemoteDeviceSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteDeviceSvc) EXPECT() *MockRemoteDeviceSvcMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRemoteDeviceSvc) Add(ctx context.Context, req remote_device_svc.AddRequest) (*remote_device_svc.DeviceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, req)
	ret0, _ := ret[0].(*remote_device_svc.DeviceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockRemoteDeviceSvcMockRecorder) Add(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).Add), ctx, req)
}

// Get mocks base method.
func (m *MockRemoteDeviceSvc) Get(ctx context.Context, id int64) (*remote_device_svc.DeviceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*remote_device_svc.DeviceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRemoteDeviceSvcMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockRemoteDeviceSvc) List(ctx context.Context) ([]*remote_device_svc.DeviceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*remote_device_svc.DeviceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRemoteDeviceSvcMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).List), ctx)
}

// ListDeviceProviders mocks base method.
func (m *MockRemoteDeviceSvc) ListDeviceProviders(deviceID int64) []remote_device_svc.ProviderSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeviceProviders", deviceID)
	ret0, _ := ret[0].([]remote_device_svc.ProviderSummary)
	return ret0
}

// ListDeviceProviders indicates an expected call of ListDeviceProviders.
func (mr *MockRemoteDeviceSvcMockRecorder) ListDeviceProviders(deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeviceProviders", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).ListDeviceProviders), deviceID)
}

// Pool mocks base method.
func (m *MockRemoteDeviceSvc) Pool() remote_device_svc.ConnPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pool")
	ret0, _ := ret[0].(remote_device_svc.ConnPool)
	return ret0
}

// Pool indicates an expected call of Pool.
func (mr *MockRemoteDeviceSvcMockRecorder) Pool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pool", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).Pool))
}

// RecordDeviceProviders mocks base method.
func (m *MockRemoteDeviceSvc) RecordDeviceProviders(deviceID int64, ps []remote_device_svc.ProviderSummary) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDeviceProviders", deviceID, ps)
}

// RecordDeviceProviders indicates an expected call of RecordDeviceProviders.
func (mr *MockRemoteDeviceSvcMockRecorder) RecordDeviceProviders(deviceID, ps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDeviceProviders", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).RecordDeviceProviders), deviceID, ps)
}

// Refresh mocks base method.
func (m *MockRemoteDeviceSvc) Refresh(ctx context.Context, id int64) (*remote_device_svc.DeviceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, id)
	ret0, _ := ret[0].(*remote_device_svc.DeviceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockRemoteDeviceSvcMockRecorder) Refresh(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).Refresh), ctx, id)
}

// Remove mocks base method.
func (m *MockRemoteDeviceSvc) Remove(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRemoteDeviceSvcMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).Remove), ctx, id)
}

// Rename mocks base method.
func (m *MockRemoteDeviceSvc) Rename(ctx context.Context, id int64, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockRemoteDeviceSvcMockRecorder) Rename(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).Rename), ctx, id, name)
}

// SetWatcher mocks base method.
func (m *MockRemoteDeviceSvc) SetWatcher(w remote_device_svc.WatcherPort) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWatcher", w)
}

// SetWatcher indicates an expected call of SetWatcher.
func (mr *MockRemoteDeviceSvcMockRecorder) SetWatcher(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWatcher", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).SetWatcher), w)
}

// SyncProvider mocks base method.
func (m *MockRemoteDeviceSvc) SyncProvider(ctx context.Context, deviceID int64, providerKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncProvider", ctx, deviceID, providerKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncProvider indicates an expected call of SyncProvider.
func (mr *MockRemoteDeviceSvcMockRecorder) SyncProvider(ctx, deviceID, providerKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncProvider", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).SyncProvider), ctx, deviceID, providerKey)
}

// UpdateTLS mocks base method.
func (m *MockRemoteDeviceSvc) UpdateTLS(ctx context.Context, id int64, mode, pem string) (*remote_device_svc.DeviceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTLS", ctx, id, mode, pem)
	ret0, _ := ret[0].(*remote_device_svc.DeviceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTLS indicates an expected call of UpdateTLS.
func (mr *MockRemoteDeviceSvcMockRecorder) UpdateTLS(ctx, id, mode, pem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTLS", reflect.TypeOf((*MockRemoteDeviceSvc)(nil).UpdateTLS), ctx, id, mode, pem)
}
