// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_remote_device_svc/mock_ports.go
//

// Package mock_remote_device_svc is a generated GoMock package.
package mock_remote_device_svc

import (
	context "context"
	client "github.com/agentre-ai/agentre/internal/daemon/client"
	remote_device_svc "github.com/agentre-ai/agentre/internal/service/remote_device_svc"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDaemonDialPort is a mock of DaemonDialPort interface.
type MockDaemonDialPort struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonDialPortMockRecorder
	isgomock struct{}
}

// MockDaemonDialPortMockRecorder is the mock recorder for MockDaemonDialPort.
type MockDaemonDialPortMockRecorder struct {
	mock *MockDaemonDialPort
}

// NewMockDaemonDialPort creates a new mock instance.
func NewMockDaemonDialPort(ctrl *gomock.Controller) *MockDaemonDialPort {
	mock := &MockDaemonDialPort{ctrl: ctrl}
	mock.recorder = &MockDaemonDialPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemonDialPort) EXPECT() *MockDaemonDialPortMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockDaemonDialPort) Connect(ctx context.Context, args remote_device_svc.ConnectArgs) (remote_device_svc.ConnectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, args)
	ret0, _ := ret[0].(remote_device_svc.ConnectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockDaemonDialPortMockRecorder) Connect(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDaemonDialPort)(nil).Connect), ctx, args)
}

// Open mocks base method.
func (m *MockDaemonDialPort) Open(ctx context.Context, args remote_device_svc.ConnectArgs) (*client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, args)
	ret0, _ := ret[0].(*client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockDaemonDialPortMockRecorder) Open(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockDaemonDialPort)(nil).Open), ctx, args)
}

// Pair mocks base method.
func (m *MockDaemonDialPort) Pair(ctx context.Context, args remote_device_svc.PairArgs) (remote_device_svc.PairResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pair", ctx, args)
	ret0, _ := ret[0].(remote_device_svc.PairResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pair indicates an expected call of Pair.
func (mr *MockDaemonDialPortMockRecorder) Pair(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pair", reflect.TypeOf((*MockDaemonDialPort)(nil).Pair), ctx, args)
}

// MockKeychainPort is a mock of KeychainPort interface.
type MockKeychainPort struct {
	ctrl     *gomock.Controller
	recorder *MockKeychainPortMockRecorder
	isgomock struct{}
}

// MockKeychainPortMockRecorder is the mock recorder for MockKeychainPort.
type MockKeychainPortMockRecorder struct {
	mock *MockKeychainPort
}

// NewMockKeychainPort creates a new mock instance.
func NewMockKeychainPort(ctrl *gomock.Controller) *MockKeychainPort {
	mock := &MockKeychainPort{ctrl: ctrl}
	mock.recorder = &MockKeychainPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeychainPort) EXPECT() *MockKeychainPortMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockKeychainPort) Delete(account string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKeychainPortMockRecorder) Delete(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKeychainPort)(nil).Delete), account)
}

// Get mocks base method.
func (m *MockKeychainPort) Get(account string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKeychainPortMockRecorder) Get(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKeychainPort)(nil).Get), account)
}

// Set mocks base method.
func (m *MockKeychainPort) Set(account, secret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", account, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockKeychainPortMockRecorder) Set(account, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockKeychainPort)(nil).Set), account, secret)
}

// MockWatcherPort is a mock of WatcherPort interface.
type MockWatcherPort struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherPortMockRecorder
	isgomock struct{}
}

// MockWatcherPortMockRecorder is the mock recorder for MockWatcherPort.
type MockWatcherPortMockRecorder struct {
	mock *MockWatcherPort
}

// NewMockWatcherPort creates a new mock instance.
func NewMockWatcherPort(ctrl *gomock.Controller) *MockWatcherPort {
	mock := &MockWatcherPort{ctrl: ctrl}
	mock.recorder = &MockWatcherPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcherPort) EXPECT() *MockWatcherPortMockRecorder {
	return m.recorder
}

// Restart mocks base method.
func (m *MockWatcherPort) Restart(ctx context.Context, deviceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", ctx, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restart indicates an expected call of Restart.
func (mr *MockWatcherPortMockRecorder) Restart(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockWatcherPort)(nil).Restart), ctx, deviceID)
}

// Start mocks base method.
func (m *MockWatcherPort) Start(ctx context.Context, deviceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockWatcherPortMockRecorder) Start(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWatcherPort)(nil).Start), ctx, deviceID)
}

// Stop mocks base method.
func (m *MockWatcherPort) Stop(deviceID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", deviceID)
}

// Stop indicates an expected call of Stop.
func (mr *MockWatcherPortMockRecorder) Stop(deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWatcherPort)(nil).Stop), deviceID)
}
