// Code generated by MockGen. DO NOT EDIT.
// Source: conn_pool.go
//
// Generated by this command:
//
//	mockgen -source conn_pool.go -destination mock_remote_device_svc/mock_conn_pool.go
//

// Package mock_remote_device_svc is a generated GoMock package.
package mock_remote_device_svc

import (
	agentruntime "agentre/internal/pkg/agentruntime"
	remote_device_svc "agentre/internal/service/remote_device_svc"
	context "context"
	json "encoding/json"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConnPool is a mock of ConnPool interface.
type MockConnPool struct {
	ctrl     *gomock.Controller
	recorder *MockConnPoolMockRecorder
	isgomock struct{}
}

// MockConnPoolMockRecorder is the mock recorder for MockConnPool.
type MockConnPoolMockRecorder struct {
	mock *MockConnPool
}

// NewMockConnPool creates a new mock instance.
func NewMockConnPool(ctrl *gomock.Controller) *MockConnPool {
	mock := &MockConnPool{ctrl: ctrl}
	mock.recorder = &MockConnPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnPool) EXPECT() *MockConnPoolMockRecorder {
	return m.recorder
}

// Borrow mocks base method.
func (m *MockConnPool) Borrow(ctx context.Context, deviceID int64) (remote_device_svc.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Borrow", ctx, deviceID)
	ret0, _ := ret[0].(remote_device_svc.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Borrow indicates an expected call of Borrow.
func (mr *MockConnPoolMockRecorder) Borrow(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Borrow", reflect.TypeOf((*MockConnPool)(nil).Borrow), ctx, deviceID)
}

// Close mocks base method.
func (m *MockConnPool) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConnPoolMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnPool)(nil).Close))
}

// MockLease is a mock of Lease interface.
type MockLease struct {
	ctrl     *gomock.Controller
	recorder *MockLeaseMockRecorder
	isgomock struct{}
}

// MockLeaseMockRecorder is the mock recorder for MockLease.
type MockLeaseMockRecorder struct {
	mock *MockLease
}

// NewMockLease creates a new mock instance.
func NewMockLease(ctrl *gomock.Controller) *MockLease {
	mock := &MockLease{ctrl: ctrl}
	mock.recorder = &MockLeaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLease) EXPECT() *MockLeaseMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockLease) Client() agentruntime.DaemonClientPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(agentruntime.DaemonClientPort)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockLeaseMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockLease)(nil).Client))
}

// Closed mocks base method.
func (m *MockLease) Closed() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Closed")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Closed indicates an expected call of Closed.
func (mr *MockLeaseMockRecorder) Closed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Closed", reflect.TypeOf((*MockLease)(nil).Closed))
}

// Release mocks base method.
func (m *MockLease) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockLeaseMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockLease)(nil).Release))
}

// MockpooledClient is a mock of pooledClient interface.
type MockpooledClient struct {
	ctrl     *gomock.Controller
	recorder *MockpooledClientMockRecorder
	isgomock struct{}
}

// MockpooledClientMockRecorder is the mock recorder for MockpooledClient.
type MockpooledClientMockRecorder struct {
	mock *MockpooledClient
}

// NewMockpooledClient creates a new mock instance.
func NewMockpooledClient(ctrl *gomock.Controller) *MockpooledClient {
	mock := &MockpooledClient{ctrl: ctrl}
	mock.recorder = &MockpooledClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpooledClient) EXPECT() *MockpooledClientMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockpooledClient) Call(ctx context.Context, method string, params, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, method, params, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockpooledClientMockRecorder) Call(ctx, method, params, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockpooledClient)(nil).Call), ctx, method, params, result)
}

// Close mocks base method.
func (m *MockpooledClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockpooledClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockpooledClient)(nil).Close))
}

// Closed mocks base method.
func (m *MockpooledClient) Closed() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Closed")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Closed indicates an expected call of Closed.
func (mr *MockpooledClientMockRecorder) Closed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Closed", reflect.TypeOf((*MockpooledClient)(nil).Closed))
}

// Handle mocks base method.
func (m *MockpooledClient) Handle(method string, fn func(context.Context, json.RawMessage) (any, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", method, fn)
}

// Handle indicates an expected call of Handle.
func (mr *MockpooledClientMockRecorder) Handle(method, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockpooledClient)(nil).Handle), method, fn)
}

// Notify mocks base method.
func (m *MockpooledClient) Notify(method string, params any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", method, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockpooledClientMockRecorder) Notify(method, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockpooledClient)(nil).Notify), method, params)
}
