// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_remote_device_watcher_svc/mock_ports.go
//

// Package mock_remote_device_watcher_svc is a generated GoMock package.
package mock_remote_device_watcher_svc

import (
	client "agentre/internal/daemon/client"
	paired_agentred_entity "agentre/internal/model/entity/paired_agentred_entity"
	remote_device_watcher_svc "agentre/internal/service/remote_device_watcher_svc"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDaemonDialPort is a mock of DaemonDialPort interface.
type MockDaemonDialPort struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonDialPortMockRecorder
	isgomock struct{}
}

// MockDaemonDialPortMockRecorder is the mock recorder for MockDaemonDialPort.
type MockDaemonDialPortMockRecorder struct {
	mock *MockDaemonDialPort
}

// NewMockDaemonDialPort creates a new mock instance.
func NewMockDaemonDialPort(ctrl *gomock.Controller) *MockDaemonDialPort {
	mock := &MockDaemonDialPort{ctrl: ctrl}
	mock.recorder = &MockDaemonDialPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemonDialPort) EXPECT() *MockDaemonDialPortMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockDaemonDialPort) Open(ctx context.Context, args remote_device_watcher_svc.OpenArgs) (*client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, args)
	ret0, _ := ret[0].(*client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockDaemonDialPortMockRecorder) Open(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockDaemonDialPort)(nil).Open), ctx, args)
}

// MockKeychainPort is a mock of KeychainPort interface.
type MockKeychainPort struct {
	ctrl     *gomock.Controller
	recorder *MockKeychainPortMockRecorder
	isgomock struct{}
}

// MockKeychainPortMockRecorder is the mock recorder for MockKeychainPort.
type MockKeychainPortMockRecorder struct {
	mock *MockKeychainPort
}

// NewMockKeychainPort creates a new mock instance.
func NewMockKeychainPort(ctrl *gomock.Controller) *MockKeychainPort {
	mock := &MockKeychainPort{ctrl: ctrl}
	mock.recorder = &MockKeychainPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeychainPort) EXPECT() *MockKeychainPortMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockKeychainPort) Get(account string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKeychainPortMockRecorder) Get(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKeychainPort)(nil).Get), account)
}

// MockPairedAgentredReader is a mock of PairedAgentredReader interface.
type MockPairedAgentredReader struct {
	ctrl     *gomock.Controller
	recorder *MockPairedAgentredReaderMockRecorder
	isgomock struct{}
}

// MockPairedAgentredReaderMockRecorder is the mock recorder for MockPairedAgentredReader.
type MockPairedAgentredReaderMockRecorder struct {
	mock *MockPairedAgentredReader
}

// NewMockPairedAgentredReader creates a new mock instance.
func NewMockPairedAgentredReader(ctrl *gomock.Controller) *MockPairedAgentredReader {
	mock := &MockPairedAgentredReader{ctrl: ctrl}
	mock.recorder = &MockPairedAgentredReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPairedAgentredReader) EXPECT() *MockPairedAgentredReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPairedAgentredReader) Get(ctx context.Context, id int64) (*paired_agentred_entity.PairedAgentred, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*paired_agentred_entity.PairedAgentred)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPairedAgentredReaderMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPairedAgentredReader)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockPairedAgentredReader) List(ctx context.Context) ([]*paired_agentred_entity.PairedAgentred, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*paired_agentred_entity.PairedAgentred)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPairedAgentredReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPairedAgentredReader)(nil).List), ctx)
}

// UpdateLastSeen mocks base method.
func (m *MockPairedAgentredReader) UpdateLastSeen(ctx context.Context, id, lastSeenAtMs int64, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastSeen", ctx, id, lastSeenAtMs, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastSeen indicates an expected call of UpdateLastSeen.
func (mr *MockPairedAgentredReaderMockRecorder) UpdateLastSeen(ctx, id, lastSeenAtMs, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastSeen", reflect.TypeOf((*MockPairedAgentredReader)(nil).UpdateLastSeen), ctx, id, lastSeenAtMs, lastError)
}

// MockEmitter is a mock of Emitter interface.
type MockEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockEmitterMockRecorder
	isgomock struct{}
}

// MockEmitterMockRecorder is the mock recorder for MockEmitter.
type MockEmitterMockRecorder struct {
	mock *MockEmitter
}

// NewMockEmitter creates a new mock instance.
func NewMockEmitter(ctrl *gomock.Controller) *MockEmitter {
	mock := &MockEmitter{ctrl: ctrl}
	mock.recorder = &MockEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmitter) EXPECT() *MockEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockEmitter) Emit(payload remote_device_watcher_svc.StateEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", payload)
}

// Emit indicates an expected call of Emit.
func (mr *MockEmitterMockRecorder) Emit(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockEmitter)(nil).Emit), payload)
}

// MockProviderRecorder is a mock of ProviderRecorder interface.
type MockProviderRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockProviderRecorderMockRecorder
	isgomock struct{}
}

// MockProviderRecorderMockRecorder is the mock recorder for MockProviderRecorder.
type MockProviderRecorderMockRecorder struct {
	mock *MockProviderRecorder
}

// NewMockProviderRecorder creates a new mock instance.
func NewMockProviderRecorder(ctrl *gomock.Controller) *MockProviderRecorder {
	mock := &MockProviderRecorder{ctrl: ctrl}
	mock.recorder = &MockProviderRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderRecorder) EXPECT() *MockProviderRecorderMockRecorder {
	return m.recorder
}

// RecordDeviceProviders mocks base method.
func (m *MockProviderRecorder) RecordDeviceProviders(deviceID int64, ps []remote_device_watcher_svc.ProviderSummary) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDeviceProviders", deviceID, ps)
}

// RecordDeviceProviders indicates an expected call of RecordDeviceProviders.
func (mr *MockProviderRecorderMockRecorder) RecordDeviceProviders(deviceID, ps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDeviceProviders", reflect.TypeOf((*MockProviderRecorder)(nil).RecordDeviceProviders), deviceID, ps)
}
