// Code generated by MockGen. DO NOT EDIT.
// Source: department.go
//
// Generated by this command:
//
//	mockgen -source department.go -destination mock_department_repo/mock_department.go
//

// Package mock_department_repo is a generated GoMock package.
package mock_department_repo

import (
	context "context"
	department_entity "github.com/agentre-ai/agentre/internal/model/entity/department_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDepartmentRepo is a mock of DepartmentRepo interface.
type MockDepartmentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepoMockRecorder
	isgomock struct{}
}

// MockDepartmentRepoMockRecorder is the mock recorder for MockDepartmentRepo.
type MockDepartmentRepoMockRecorder struct {
	mock *MockDepartmentRepo
}

// NewMockDepartmentRepo creates a new mock instance.
func NewMockDepartmentRepo(ctrl *gomock.Controller) *MockDepartmentRepo {
	mock := &MockDepartmentRepo{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepo) EXPECT() *MockDepartmentRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepartmentRepo) Create(ctx context.Context, d *department_entity.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDepartmentRepoMockRecorder) Create(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartmentRepo)(nil).Create), ctx, d)
}

// Delete mocks base method.
func (m *MockDepartmentRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartmentRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartmentRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockDepartmentRepo) Find(ctx context.Context, id int64) (*department_entity.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*department_entity.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockDepartmentRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDepartmentRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockDepartmentRepo) FindByName(ctx context.Context, name string, parentID int64) (*department_entity.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name, parentID)
	ret0, _ := ret[0].(*department_entity.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockDepartmentRepoMockRecorder) FindByName(ctx, name, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockDepartmentRepo)(nil).FindByName), ctx, name, parentID)
}

// List mocks base method.
func (m *MockDepartmentRepo) List(ctx context.Context) ([]*department_entity.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*department_entity.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDepartmentRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDepartmentRepo)(nil).List), ctx)
}

// ListByParent mocks base method.
func (m *MockDepartmentRepo) ListByParent(ctx context.Context, parentID int64) ([]*department_entity.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByParent", ctx, parentID)
	ret0, _ := ret[0].([]*department_entity.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByParent indicates an expected call of ListByParent.
func (mr *MockDepartmentRepoMockRecorder) ListByParent(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByParent", reflect.TypeOf((*MockDepartmentRepo)(nil).ListByParent), ctx, parentID)
}

// NextSortOrder mocks base method.
func (m *MockDepartmentRepo) NextSortOrder(ctx context.Context, parentID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSortOrder", ctx, parentID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSortOrder indicates an expected call of NextSortOrder.
func (mr *MockDepartmentRepoMockRecorder) NextSortOrder(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSortOrder", reflect.TypeOf((*MockDepartmentRepo)(nil).NextSortOrder), ctx, parentID)
}

// ReparentChildren mocks base method.
func (m *MockDepartmentRepo) ReparentChildren(ctx context.Context, fromID, toParentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReparentChildren", ctx, fromID, toParentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReparentChildren indicates an expected call of ReparentChildren.
func (mr *MockDepartmentRepoMockRecorder) ReparentChildren(ctx, fromID, toParentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReparentChildren", reflect.TypeOf((*MockDepartmentRepo)(nil).ReparentChildren), ctx, fromID, toParentID)
}

// Update mocks base method.
func (m *MockDepartmentRepo) Update(ctx context.Context, d *department_entity.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDepartmentRepoMockRecorder) Update(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentRepo)(nil).Update), ctx, d)
}
