// Code generated by MockGen. DO NOT EDIT.
// Source: llm_provider.go
//
// Generated by this command:
//
//	mockgen -source llm_provider.go -destination mock_llm_provider_repo/mock_llm_provider.go
//

// Package mock_llm_provider_repo is a generated GoMock package.
package mock_llm_provider_repo

import (
	llm_provider_entity "agentre/internal/model/entity/llm_provider_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLLMProviderRepo is a mock of LLMProviderRepo interface.
type MockLLMProviderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderRepoMockRecorder
	isgomock struct{}
}

// MockLLMProviderRepoMockRecorder is the mock recorder for MockLLMProviderRepo.
type MockLLMProviderRepoMockRecorder struct {
	mock *MockLLMProviderRepo
}

// NewMockLLMProviderRepo creates a new mock instance.
func NewMockLLMProviderRepo(ctrl *gomock.Controller) *MockLLMProviderRepo {
	mock := &MockLLMProviderRepo{ctrl: ctrl}
	mock.recorder = &MockLLMProviderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProviderRepo) EXPECT() *MockLLMProviderRepoMockRecorder {
	return m.recorder
}

// BatchFindByKey mocks base method.
func (m *MockLLMProviderRepo) BatchFindByKey(ctx context.Context, keys []string) (map[string]*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchFindByKey", ctx, keys)
	ret0, _ := ret[0].(map[string]*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchFindByKey indicates an expected call of BatchFindByKey.
func (mr *MockLLMProviderRepoMockRecorder) BatchFindByKey(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchFindByKey", reflect.TypeOf((*MockLLMProviderRepo)(nil).BatchFindByKey), ctx, keys)
}

// Create mocks base method.
func (m *MockLLMProviderRepo) Create(ctx context.Context, p *llm_provider_entity.LLMProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLLMProviderRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLLMProviderRepo)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockLLMProviderRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLLMProviderRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLLMProviderRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockLLMProviderRepo) Find(ctx context.Context, id int64) (*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockLLMProviderRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLLMProviderRepo)(nil).Find), ctx, id)
}

// FindByKey mocks base method.
func (m *MockLLMProviderRepo) FindByKey(ctx context.Context, key string) (*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKey", ctx, key)
	ret0, _ := ret[0].(*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKey indicates an expected call of FindByKey.
func (mr *MockLLMProviderRepoMockRecorder) FindByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKey", reflect.TypeOf((*MockLLMProviderRepo)(nil).FindByKey), ctx, key)
}

// FindByName mocks base method.
func (m *MockLLMProviderRepo) FindByName(ctx context.Context, name string) (*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockLLMProviderRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockLLMProviderRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockLLMProviderRepo) List(ctx context.Context) ([]*llm_provider_entity.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*llm_provider_entity.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLLMProviderRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLLMProviderRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockLLMProviderRepo) Update(ctx context.Context, p *llm_provider_entity.LLMProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLLMProviderRepoMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLLMProviderRepo)(nil).Update), ctx, p)
}
