// Code generated by MockGen. DO NOT EDIT.
// Source: agent_backend.go
//
// Generated by this command:
//
//	mockgen -source agent_backend.go -destination mock_agent_backend_repo/mock_agent_backend.go
//

// Package mock_agent_backend_repo is a generated GoMock package.
package mock_agent_backend_repo

import (
	agent_backend_entity "agentre/internal/model/entity/agent_backend_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAgentBackendRepo is a mock of AgentBackendRepo interface.
type MockAgentBackendRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentBackendRepoMockRecorder
	isgomock struct{}
}

// MockAgentBackendRepoMockRecorder is the mock recorder for MockAgentBackendRepo.
type MockAgentBackendRepoMockRecorder struct {
	mock *MockAgentBackendRepo
}

// NewMockAgentBackendRepo creates a new mock instance.
func NewMockAgentBackendRepo(ctrl *gomock.Controller) *MockAgentBackendRepo {
	mock := &MockAgentBackendRepo{ctrl: ctrl}
	mock.recorder = &MockAgentBackendRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentBackendRepo) EXPECT() *MockAgentBackendRepoMockRecorder {
	return m.recorder
}

// BatchFind mocks base method.
func (m *MockAgentBackendRepo) BatchFind(ctx context.Context, ids []int64) (map[int64]*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchFind", ctx, ids)
	ret0, _ := ret[0].(map[int64]*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchFind indicates an expected call of BatchFind.
func (mr *MockAgentBackendRepoMockRecorder) BatchFind(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchFind", reflect.TypeOf((*MockAgentBackendRepo)(nil).BatchFind), ctx, ids)
}

// Create mocks base method.
func (m *MockAgentBackendRepo) Create(ctx context.Context, b *agent_backend_entity.AgentBackend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAgentBackendRepoMockRecorder) Create(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentBackendRepo)(nil).Create), ctx, b)
}

// Delete mocks base method.
func (m *MockAgentBackendRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentBackendRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentBackendRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockAgentBackendRepo) Find(ctx context.Context, id int64) (*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentBackendRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentBackendRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockAgentBackendRepo) FindByName(ctx context.Context, name string) (*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockAgentBackendRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockAgentBackendRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockAgentBackendRepo) List(ctx context.Context) ([]*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentBackendRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentBackendRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockAgentBackendRepo) Update(ctx context.Context, b *agent_backend_entity.AgentBackend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAgentBackendRepoMockRecorder) Update(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentBackendRepo)(nil).Update), ctx, b)
}
