// Package handlers implements each JSON-RPC method as a thin function.
// All external dependencies enter via the Port interfaces defined here,
// so handler unit tests can inject mocks generated by `make mock`.
package handlers

import (
	"context"
	"time"

	"github.com/agentre-ai/agentre/internal/daemon/state"
	"github.com/agentre-ai/agentre/internal/model/entity/agent_backend_entity"
	"github.com/agentre-ai/agentre/internal/model/entity/llm_provider_entity"
)

//go:generate mockgen -source ports.go -destination mock_handlers/mock_ports.go -package mock_handlers

// StatePort is the subset of *state.State consumed by handlers. State itself
// satisfies this — defining the interface here keeps tests mockable without
// coupling the state package to consumer details.
type StatePort interface {
	Mutate(func(*state.State))
	Save() error
	Snapshot() state.State
}

// SessionHandle is what the registry stores per active chat session.
type SessionHandle struct {
	SessionID   string
	BackendType string
	Workdir     string
	StartedAt   int64
	Cancel      func()
}

// SessionRegistryPort is the in-mem session map.
type SessionRegistryPort interface {
	Register(sessionID string, h SessionHandle)
	Lookup(sessionID string) (SessionHandle, bool)
	Remove(sessionID string)
	List() []SessionHandle
}

// NotifierPort sends server-initiated notifications and reverse-direction
// requests back to the connected client (e.g. chat.event, approval.request).
type NotifierPort interface {
	Notify(method string, params any) error
	Request(ctx context.Context, method string, params any, result any) error
}

// GatewayPort daemon-side LLM gateway 端口：给 CLI 子进程签短 token、查 URL、回收 token。
// 当前由 cli.* handler 使用；chat.* 走 Runner 内部直拿 *httpgateway.Gateway 没经此端口。
// 具体实现 *httpgateway.Gateway 自然满足本接口（方法签名一致）。
type GatewayPort interface {
	URL() string
	IssueToken(ctx context.Context, b *agent_backend_entity.AgentBackend, ttl time.Duration) (string, error)
	RevokeToken(token string)
}

// LLMProviderLookupPort daemon-side LLM provider 查询端口：按稳定 UUID key 解出
// 含 APIKey 的完整 LLMProvider 实体。daemon 内 *ProviderLookup 自然满足本接口。
// 未命中按 (nil, error) 返回，调用方按 error 处理。
//
// 形状有意与 httpgateway.ProviderLookup 重合 —— 在 handlers 这边独立声明
// 是为了保留消费方 ISP，避免 internal/daemon/handlers 反向耦合到
// internal/pkg/httpgateway。
type LLMProviderLookupPort interface {
	FindByKey(ctx context.Context, key string) (*llm_provider_entity.LLMProvider, error)
}
