// Code generated by MockGen. DO NOT EDIT.
// Source: label.go
//
// Generated by this command:
//
//	mockgen -source label.go -destination mock_issue_repo/mock_label.go
//

// Package mock_issue_repo is a generated GoMock package.
package mock_issue_repo

import (
	issue_entity "agentre/internal/model/entity/issue_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLabelRepo is a mock of LabelRepo interface.
type MockLabelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLabelRepoMockRecorder
	isgomock struct{}
}

// MockLabelRepoMockRecorder is the mock recorder for MockLabelRepo.
type MockLabelRepoMockRecorder struct {
	mock *MockLabelRepo
}

// NewMockLabelRepo creates a new mock instance.
func NewMockLabelRepo(ctrl *gomock.Controller) *MockLabelRepo {
	mock := &MockLabelRepo{ctrl: ctrl}
	mock.recorder = &MockLabelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabelRepo) EXPECT() *MockLabelRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockLabelRepo) Find(ctx context.Context, id int64) (*issue_entity.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*issue_entity.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockLabelRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLabelRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockLabelRepo) List(ctx context.Context) ([]*issue_entity.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*issue_entity.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLabelRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLabelRepo)(nil).List), ctx)
}

// ListByIDs mocks base method.
func (m *MockLabelRepo) ListByIDs(ctx context.Context, ids []int64) ([]*issue_entity.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]*issue_entity.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockLabelRepoMockRecorder) ListByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockLabelRepo)(nil).ListByIDs), ctx, ids)
}

// MockIssueLabelRepo is a mock of IssueLabelRepo interface.
type MockIssueLabelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIssueLabelRepoMockRecorder
	isgomock struct{}
}

// MockIssueLabelRepoMockRecorder is the mock recorder for MockIssueLabelRepo.
type MockIssueLabelRepoMockRecorder struct {
	mock *MockIssueLabelRepo
}

// NewMockIssueLabelRepo creates a new mock instance.
func NewMockIssueLabelRepo(ctrl *gomock.Controller) *MockIssueLabelRepo {
	mock := &MockIssueLabelRepo{ctrl: ctrl}
	mock.recorder = &MockIssueLabelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueLabelRepo) EXPECT() *MockIssueLabelRepoMockRecorder {
	return m.recorder
}

// ListByIssue mocks base method.
func (m *MockIssueLabelRepo) ListByIssue(ctx context.Context, issueID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIssue", ctx, issueID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIssue indicates an expected call of ListByIssue.
func (mr *MockIssueLabelRepoMockRecorder) ListByIssue(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIssue", reflect.TypeOf((*MockIssueLabelRepo)(nil).ListByIssue), ctx, issueID)
}

// ListByIssues mocks base method.
func (m *MockIssueLabelRepo) ListByIssues(ctx context.Context, issueIDs []int64) (map[int64][]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIssues", ctx, issueIDs)
	ret0, _ := ret[0].(map[int64][]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIssues indicates an expected call of ListByIssues.
func (mr *MockIssueLabelRepoMockRecorder) ListByIssues(ctx, issueIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIssues", reflect.TypeOf((*MockIssueLabelRepo)(nil).ListByIssues), ctx, issueIDs)
}

// SetLabels mocks base method.
func (m *MockIssueLabelRepo) SetLabels(ctx context.Context, issueID int64, labelIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLabels", ctx, issueID, labelIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLabels indicates an expected call of SetLabels.
func (mr *MockIssueLabelRepoMockRecorder) SetLabels(ctx, issueID, labelIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLabels", reflect.TypeOf((*MockIssueLabelRepo)(nil).SetLabels), ctx, issueID, labelIDs)
}
