// Code generated by MockGen. DO NOT EDIT.
// Source: issue.go
//
// Generated by this command:
//
//	mockgen -source issue.go -destination mock_issue_repo/mock_issue.go
//

// Package mock_issue_repo is a generated GoMock package.
package mock_issue_repo

import (
	context "context"
	issue_entity "github.com/agentre-ai/agentre/internal/model/entity/issue_entity"
	issue_repo "github.com/agentre-ai/agentre/internal/repository/issue_repo"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIssueRepo is a mock of IssueRepo interface.
type MockIssueRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIssueRepoMockRecorder
	isgomock struct{}
}

// MockIssueRepoMockRecorder is the mock recorder for MockIssueRepo.
type MockIssueRepoMockRecorder struct {
	mock *MockIssueRepo
}

// NewMockIssueRepo creates a new mock instance.
func NewMockIssueRepo(ctrl *gomock.Controller) *MockIssueRepo {
	mock := &MockIssueRepo{ctrl: ctrl}
	mock.recorder = &MockIssueRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueRepo) EXPECT() *MockIssueRepoMockRecorder {
	return m.recorder
}

// CountByState mocks base method.
func (m *MockIssueRepo) CountByState(ctx context.Context, projectID int64) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByState", ctx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountByState indicates an expected call of CountByState.
func (mr *MockIssueRepoMockRecorder) CountByState(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByState", reflect.TypeOf((*MockIssueRepo)(nil).CountByState), ctx, projectID)
}

// Create mocks base method.
func (m *MockIssueRepo) Create(ctx context.Context, i *issue_entity.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIssueRepoMockRecorder) Create(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueRepo)(nil).Create), ctx, i)
}

// Delete mocks base method.
func (m *MockIssueRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIssueRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIssueRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockIssueRepo) Find(ctx context.Context, id int64) (*issue_entity.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*issue_entity.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIssueRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIssueRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockIssueRepo) List(ctx context.Context, filter issue_repo.ListFilter) ([]*issue_entity.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*issue_entity.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIssueRepoMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIssueRepo)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockIssueRepo) Update(ctx context.Context, i *issue_entity.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIssueRepoMockRecorder) Update(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueRepo)(nil).Update), ctx, i)
}
