// Code generated by MockGen. DO NOT EDIT.
// Source: app_setting.go
//
// Generated by this command:
//
//	mockgen -source app_setting.go -destination mock_app_setting_repo/mock_app_setting.go
//

// Package mock_app_setting_repo is a generated GoMock package.
package mock_app_setting_repo

import (
	context "context"
	app_setting_entity "github.com/agentre-ai/agentre/internal/model/entity/app_setting_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAppSettingRepo is a mock of AppSettingRepo interface.
type MockAppSettingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAppSettingRepoMockRecorder
	isgomock struct{}
}

// MockAppSettingRepoMockRecorder is the mock recorder for MockAppSettingRepo.
type MockAppSettingRepoMockRecorder struct {
	mock *MockAppSettingRepo
}

// NewMockAppSettingRepo creates a new mock instance.
func NewMockAppSettingRepo(ctrl *gomock.Controller) *MockAppSettingRepo {
	mock := &MockAppSettingRepo{ctrl: ctrl}
	mock.recorder = &MockAppSettingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppSettingRepo) EXPECT() *MockAppSettingRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAppSettingRepo) Get(ctx context.Context, key string) (*app_setting_entity.AppSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*app_setting_entity.AppSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAppSettingRepoMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAppSettingRepo)(nil).Get), ctx, key)
}

// List mocks base method.
func (m *MockAppSettingRepo) List(ctx context.Context) ([]*app_setting_entity.AppSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*app_setting_entity.AppSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAppSettingRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAppSettingRepo)(nil).List), ctx)
}

// Set mocks base method.
func (m *MockAppSettingRepo) Set(ctx context.Context, s *app_setting_entity.AppSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockAppSettingRepoMockRecorder) Set(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockAppSettingRepo)(nil).Set), ctx, s)
}
