// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination mock_project_location_svc/mock_svc.go
//

// Package mock_project_location_svc is a generated GoMock package.
package mock_project_location_svc

import (
	project_location_svc "agentre/internal/service/project_location_svc"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectLocationSvc is a mock of ProjectLocationSvc interface.
type MockProjectLocationSvc struct {
	ctrl     *gomock.Controller
	recorder *MockProjectLocationSvcMockRecorder
	isgomock struct{}
}

// MockProjectLocationSvcMockRecorder is the mock recorder for MockProjectLocationSvc.
type MockProjectLocationSvcMockRecorder struct {
	mock *MockProjectLocationSvc
}

// NewMockProjectLocationSvc creates a new mock instance.
func NewMockProjectLocationSvc(ctrl *gomock.Controller) *MockProjectLocationSvc {
	mock := &MockProjectLocationSvc{ctrl: ctrl}
	mock.recorder = &MockProjectLocationSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectLocationSvc) EXPECT() *MockProjectLocationSvcMockRecorder {
	return m.recorder
}

// ListByProject mocks base method.
func (m *MockProjectLocationSvc) ListByProject(ctx context.Context, projectID int64) ([]*project_location_svc.ProjectLocationView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID)
	ret0, _ := ret[0].([]*project_location_svc.ProjectLocationView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockProjectLocationSvcMockRecorder) ListByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockProjectLocationSvc)(nil).ListByProject), ctx, projectID)
}

// RemoveByProjectAndDevice mocks base method.
func (m *MockProjectLocationSvc) RemoveByProjectAndDevice(ctx context.Context, projectID int64, deviceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveByProjectAndDevice", ctx, projectID, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveByProjectAndDevice indicates an expected call of RemoveByProjectAndDevice.
func (mr *MockProjectLocationSvcMockRecorder) RemoveByProjectAndDevice(ctx, projectID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveByProjectAndDevice", reflect.TypeOf((*MockProjectLocationSvc)(nil).RemoveByProjectAndDevice), ctx, projectID, deviceID)
}

// Upsert mocks base method.
func (m *MockProjectLocationSvc) Upsert(ctx context.Context, projectID int64, deviceID, path string) (*project_location_svc.ProjectLocationView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, projectID, deviceID, path)
	ret0, _ := ret[0].(*project_location_svc.ProjectLocationView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockProjectLocationSvcMockRecorder) Upsert(ctx, projectID, deviceID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockProjectLocationSvc)(nil).Upsert), ctx, projectID, deviceID, path)
}
