// Code generated by MockGen. DO NOT EDIT.
// Source: project_location.go
//
// Generated by this command:
//
//	mockgen -source project_location.go -destination mock_project_location_repo/mock_project_location.go
//

// Package mock_project_location_repo is a generated GoMock package.
package mock_project_location_repo

import (
	context "context"
	project_location_entity "github.com/agentre-ai/agentre/internal/model/entity/project_location_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectLocationRepo is a mock of ProjectLocationRepo interface.
type MockProjectLocationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProjectLocationRepoMockRecorder
	isgomock struct{}
}

// MockProjectLocationRepoMockRecorder is the mock recorder for MockProjectLocationRepo.
type MockProjectLocationRepoMockRecorder struct {
	mock *MockProjectLocationRepo
}

// NewMockProjectLocationRepo creates a new mock instance.
func NewMockProjectLocationRepo(ctrl *gomock.Controller) *MockProjectLocationRepo {
	mock := &MockProjectLocationRepo{ctrl: ctrl}
	mock.recorder = &MockProjectLocationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectLocationRepo) EXPECT() *MockProjectLocationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectLocationRepo) Create(ctx context.Context, p *project_location_entity.ProjectLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectLocationRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectLocationRepo)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockProjectLocationRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectLocationRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectLocationRepo)(nil).Delete), ctx, id)
}

// FindByProjectAndDevice mocks base method.
func (m *MockProjectLocationRepo) FindByProjectAndDevice(ctx context.Context, projectID int64, deviceID string) (*project_location_entity.ProjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectAndDevice", ctx, projectID, deviceID)
	ret0, _ := ret[0].(*project_location_entity.ProjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectAndDevice indicates an expected call of FindByProjectAndDevice.
func (mr *MockProjectLocationRepoMockRecorder) FindByProjectAndDevice(ctx, projectID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectAndDevice", reflect.TypeOf((*MockProjectLocationRepo)(nil).FindByProjectAndDevice), ctx, projectID, deviceID)
}

// Get mocks base method.
func (m *MockProjectLocationRepo) Get(ctx context.Context, id int64) (*project_location_entity.ProjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*project_location_entity.ProjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectLocationRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjectLocationRepo)(nil).Get), ctx, id)
}

// ListByProject mocks base method.
func (m *MockProjectLocationRepo) ListByProject(ctx context.Context, projectID int64) ([]*project_location_entity.ProjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID)
	ret0, _ := ret[0].([]*project_location_entity.ProjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockProjectLocationRepoMockRecorder) ListByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockProjectLocationRepo)(nil).ListByProject), ctx, projectID)
}

// UpdatePath mocks base method.
func (m *MockProjectLocationRepo) UpdatePath(ctx context.Context, id int64, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePath", ctx, id, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePath indicates an expected call of UpdatePath.
func (mr *MockProjectLocationRepoMockRecorder) UpdatePath(ctx, id, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePath", reflect.TypeOf((*MockProjectLocationRepo)(nil).UpdatePath), ctx, id, path)
}
