// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mock_skill_svc/mock_deps.go -package mock_skill_svc
//

// Package mock_skill_svc is a generated GoMock package.
package mock_skill_svc

import (
	context "context"
	reflect "reflect"

	agent_backend_entity "github.com/agentre-ai/agentre/internal/model/entity/agent_backend_entity"
	agent_entity "github.com/agentre-ai/agentre/internal/model/entity/agent_entity"
	agentskill "github.com/agentre-ai/agentre/internal/pkg/agentskill"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentLookup is a mock of AgentLookup interface.
type MockAgentLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAgentLookupMockRecorder
	isgomock struct{}
}

// MockAgentLookupMockRecorder is the mock recorder for MockAgentLookup.
type MockAgentLookupMockRecorder struct {
	mock *MockAgentLookup
}

// NewMockAgentLookup creates a new mock instance.
func NewMockAgentLookup(ctrl *gomock.Controller) *MockAgentLookup {
	mock := &MockAgentLookup{ctrl: ctrl}
	mock.recorder = &MockAgentLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentLookup) EXPECT() *MockAgentLookupMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentLookup) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentLookupMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentLookup)(nil).Find), ctx, id)
}

// MockBackendLookup is a mock of BackendLookup interface.
type MockBackendLookup struct {
	ctrl     *gomock.Controller
	recorder *MockBackendLookupMockRecorder
	isgomock struct{}
}

// MockBackendLookupMockRecorder is the mock recorder for MockBackendLookup.
type MockBackendLookupMockRecorder struct {
	mock *MockBackendLookup
}

// NewMockBackendLookup creates a new mock instance.
func NewMockBackendLookup(ctrl *gomock.Controller) *MockBackendLookup {
	mock := &MockBackendLookup{ctrl: ctrl}
	mock.recorder = &MockBackendLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendLookup) EXPECT() *MockBackendLookupMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockBackendLookup) Find(ctx context.Context, id int64) (*agent_backend_entity.AgentBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_backend_entity.AgentBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockBackendLookupMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockBackendLookup)(nil).Find), ctx, id)
}

// MockRemoteDiscoverer is a mock of RemoteDiscoverer interface.
type MockRemoteDiscoverer struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteDiscovererMockRecorder
	isgomock struct{}
}

// MockRemoteDiscovererMockRecorder is the mock recorder for MockRemoteDiscoverer.
type MockRemoteDiscovererMockRecorder struct {
	mock *MockRemoteDiscoverer
}

// NewMockRemoteDiscoverer creates a new mock instance.
func NewMockRemoteDiscoverer(ctrl *gomock.Controller) *MockRemoteDiscoverer {
	mock := &MockRemoteDiscoverer{ctrl: ctrl}
	mock.recorder = &MockRemoteDiscovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteDiscoverer) EXPECT() *MockRemoteDiscovererMockRecorder {
	return m.recorder
}

// ListSkills mocks base method.
func (m *MockRemoteDiscoverer) ListSkills(ctx context.Context, deviceID int64, backendType string) ([]agentskill.SkillPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", ctx, deviceID, backendType)
	ret0, _ := ret[0].([]agentskill.SkillPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockRemoteDiscovererMockRecorder) ListSkills(ctx, deviceID, backendType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockRemoteDiscoverer)(nil).ListSkills), ctx, deviceID, backendType)
}
